table dFinalidades
	lineageTag: 38544813-ed5c-4f44-a6b6-d0eedb8dbf8d

	column Finalidade
		dataType: string
		lineageTag: b7fca72e-6ce0-4438-a1d2-8f3dcb9b35b8
		summarizeBy: none
		sourceColumn: Finalidade

		annotation SummarizationSetBy = Automatic

	column Tipo
		dataType: string
		lineageTag: 2c13ec9a-b26c-42d0-9d9e-56716e00b376
		summarizeBy: none
		sourceColumn: Tipo

		annotation SummarizationSetBy = Automatic

	partition dFinalidades = m
		mode: import
		source =
				let
				    Source = GoogleSheets.Contents("https://docs.google.com/spreadsheets/d/1_Xtx0snoLOuKp9DWR1D9C6kG4rZpVVOQyo8zCd1N5fY/edit?usp=sharing"),
				    #"lista - tipos de finalidades_Table" = Source{[name="lista - tipos de finalidades",ItemKind="Table"]}[Data],
				    #"Promoted Headers" = Table.PromoteHeaders(#"lista - tipos de finalidades_Table", [PromoteAllScalars=true])
				in
				    #"Promoted Headers"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

