table Transações
	lineageTag: d4a51c54-a899-4bbd-9d9b-358e6d75fa7f

	measure 'Montante (normalizado)' = ABS(SUM('Transações'[Montante (R$)]))
		lineageTag: 9e15c4f4-8296-4d5d-86f5-41e8c8ad212d

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Linha
		dataType: int64
		formatString: 0
		lineageTag: 108fec05-e8a9-45fb-bd50-edcb41047ff9
		summarizeBy: none
		sourceColumn: Linha

		annotation SummarizationSetBy = User

	column 'Data Lançamento'
		dataType: dateTime
		formatString: Short Date
		lineageTag: e749102b-cafa-4291-a588-6ab766fb45a9
		summarizeBy: none
		sourceColumn: Data Lançamento

		annotation SummarizationSetBy = Automatic

	column 'Montante (R$)'
		dataType: double
		lineageTag: ec99ea6d-faab-40a2-a9e2-3738a69537b1
		summarizeBy: none
		sourceColumn: Montante (R$)

		annotation SummarizationSetBy = User

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Subunidade
		dataType: string
		lineageTag: eb5a8eab-6f8d-4e47-840c-ca9316e84ee5
		summarizeBy: none
		sourceColumn: Subunidade

		annotation SummarizationSetBy = Automatic

	column Natureza
		dataType: string
		lineageTag: 9b0c0850-7e18-47ca-85fd-70f234cbc88d
		summarizeBy: none
		sourceColumn: Natureza

		annotation SummarizationSetBy = Automatic

	column Finalidade
		dataType: string
		lineageTag: 14567775-6804-4adb-a195-2baf86ac8940
		summarizeBy: none
		sourceColumn: Finalidade

		annotation SummarizationSetBy = Automatic

	column Tipo
		dataType: string
		lineageTag: 430762df-2eac-422c-9771-6a7113145487
		summarizeBy: none
		sourceColumn: Tipo

		annotation SummarizationSetBy = Automatic

	column 'PEN Empenho'
		dataType: string
		lineageTag: 1dc8a474-82ee-4759-afad-79731d0f12b5
		summarizeBy: none
		sourceColumn: PEN Empenho

		annotation SummarizationSetBy = Automatic

	column 'PEN Pagamento'
		dataType: string
		lineageTag: 1a407dd0-e723-44a6-95e5-815e9ceeddbc
		summarizeBy: none
		sourceColumn: PEN Pagamento

		annotation SummarizationSetBy = Automatic

	column 'Finalidade (detalhada)'
		dataType: string
		lineageTag: f331fc9c-896b-4104-a22d-17b2dd524ee4
		summarizeBy: none
		sourceColumn: Finalidade (detalhada)

		annotation SummarizationSetBy = Automatic

	column Descrição
		dataType: string
		lineageTag: 38bda63d-76b7-4478-bd6d-8bf343d8e26d
		summarizeBy: none
		sourceColumn: Descrição

		annotation SummarizationSetBy = Automatic

	partition Transações = m
		mode: import
		source =
				let
				    Source = GoogleSheets.Contents("https://docs.google.com/spreadsheets/d/1_Xtx0snoLOuKp9DWR1D9C6kG4rZpVVOQyo8zCd1N5fY/edit?usp=sharing"),
				    NS2_Table = Source{[name="NS2",ItemKind="Table"]}[Data],
				    #"Promoted Headers" = Table.PromoteHeaders(NS2_Table, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"Linha", Int64.Type}, {"Data Lançamento", type date}, {"Montante (R$)", type number}, {"Subunidade", type text}, {"Natureza", type text}, {"Finalidade", type text}, {"Tipo", type text}, {"PEN Empenho", type text}, {"PEN Pagamento", type any}}),
				    #"Removed Blank Rows" = Table.SelectRows(#"Changed Type", each not List.IsEmpty(List.RemoveMatchingItems(Record.FieldValues(_), {"", null}))),
				    #"Changed Type1" = Table.TransformColumnTypes(#"Removed Blank Rows",{{"Data Lançamento", type datetime}})
				in
				    #"Changed Type1"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

