table Transações
	lineageTag: d4a51c54-a899-4bbd-9d9b-358e6d75fa7f

	measure Montante = ABS(SUM('Transações'[Montante (signed)]))
		formatString: "R$"\ #,0.00;-"R$"\ #,0.00;"R$"\ #,0.00
		lineageTag: 9e15c4f4-8296-4d5d-86f5-41e8c8ad212d

		annotation PBI_FormatHint = {"currencyCulture":"pt-BR"}

	column Linha
		dataType: int64
		formatString: 0
		lineageTag: 108fec05-e8a9-45fb-bd50-edcb41047ff9
		summarizeBy: none
		sourceColumn: Linha

		annotation SummarizationSetBy = User

	column 'Data Lançamento'
		dataType: dateTime
		formatString: Short Date
		lineageTag: e749102b-cafa-4291-a588-6ab766fb45a9
		summarizeBy: none
		sourceColumn: Data Lançamento

		annotation SummarizationSetBy = Automatic

	column 'Montante (signed)'
		dataType: double
		isHidden
		formatString: "R$"\ #,0.00;-"R$"\ #,0.00;"R$"\ #,0.00
		lineageTag: ec99ea6d-faab-40a2-a9e2-3738a69537b1
		summarizeBy: none
		sourceColumn: Montante (signed)

		changedProperty = IsHidden

		annotation SummarizationSetBy = User

		annotation PBI_FormatHint = {"currencyCulture":"pt-BR"}

	column Subunidade
		dataType: string
		lineageTag: eb5a8eab-6f8d-4e47-840c-ca9316e84ee5
		summarizeBy: none
		sourceColumn: Subunidade

		annotation SummarizationSetBy = Automatic

	column Finalidade
		dataType: string
		lineageTag: 14567775-6804-4adb-a195-2baf86ac8940
		summarizeBy: none
		sourceColumn: Finalidade

		annotation SummarizationSetBy = Automatic

	column Tipo
		dataType: string
		lineageTag: 430762df-2eac-422c-9771-6a7113145487
		summarizeBy: none
		sourceColumn: Tipo

		annotation SummarizationSetBy = Automatic

	column 'Finalidade (detalhada)'
		dataType: string
		lineageTag: f331fc9c-896b-4104-a22d-17b2dd524ee4
		summarizeBy: none
		sourceColumn: Finalidade (detalhada)

		annotation SummarizationSetBy = Automatic

	column Descrição
		dataType: string
		lineageTag: 38bda63d-76b7-4478-bd6d-8bf343d8e26d
		summarizeBy: none
		sourceColumn: Descrição

		annotation SummarizationSetBy = Automatic

	column 'Tipo subunidade'
		dataType: string
		lineageTag: 67ecea68-60cd-40c9-86ee-7d90ed15de34
		summarizeBy: none
		sourceColumn: Tipo subunidade

		annotation SummarizationSetBy = Automatic

	column Pago
		dataType: string
		lineageTag: 2d0c5d08-2d15-4c43-8ce5-83e2a41bab4b
		summarizeBy: none
		sourceColumn: Pago

		annotation SummarizationSetBy = Automatic

	column 'Doc de Solitação'
		dataType: string
		lineageTag: cc619a9f-ca9f-4fc9-a35a-623adfc355f0
		summarizeBy: none
		sourceColumn: Doc de Solitação

		annotation SummarizationSetBy = Automatic

	column 'Doc de Pagamento'
		dataType: string
		lineageTag: 5e0db7aa-dbe8-4ddf-9fed-0d83cc0848b8
		summarizeBy: none
		sourceColumn: Doc de Pagamento

		annotation SummarizationSetBy = Automatic

	column 'Lista SIAFI'
		dataType: string
		lineageTag: 28700cbc-4a9e-4dc7-b318-761934029d6c
		summarizeBy: none
		sourceColumn: Lista SIAFI

		annotation SummarizationSetBy = Automatic

	column 'Empenho SIE'
		dataType: string
		lineageTag: 9f887121-315d-428a-a865-fba381d28034
		summarizeBy: none
		sourceColumn: Empenho SIE

		annotation SummarizationSetBy = Automatic

	column 'Empenho SIAFI'
		dataType: string
		lineageTag: 8a789568-1796-4f9e-ad86-65a2a5a85c6e
		summarizeBy: none
		sourceColumn: Empenho SIAFI

		annotation SummarizationSetBy = Automatic

	column 'Local / Trecho'
		dataType: string
		lineageTag: 3f7bc5ee-6ed4-4b54-bdbc-c1b08bb5b1da
		summarizeBy: none
		sourceColumn: Local / Trecho

		annotation SummarizationSetBy = Automatic

	column Quantidade
		dataType: string
		lineageTag: 7ce7d165-8b79-486c-94ce-a8e90d75b6e0
		summarizeBy: none
		sourceColumn: Quantidade

		annotation SummarizationSetBy = Automatic

	column 'Nome / Beneficiário / Setor'
		dataType: string
		lineageTag: e842bd06-edb5-41ce-b14a-64f19aa38a77
		summarizeBy: none
		sourceColumn: Nome / Beneficiário / Setor

		annotation SummarizationSetBy = Automatic

	partition Transações = m
		mode: import
		source =
				let
				    Source = GoogleSheets.Contents("https://docs.google.com/spreadsheets/d/1_Xtx0snoLOuKp9DWR1D9C6kG4rZpVVOQyo8zCd1N5fY/edit?usp=sharing"),
				    NS2_Table = Source{[name="NS2",ItemKind="Table"]}[Data],
				    #"Promoted Headers" = Table.PromoteHeaders(NS2_Table, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"Linha", Int64.Type}, {"Data Lançamento", type date}, {"Montante (R$)", type number}, {"Subunidade", type text}, {"Finalidade", type text}, {"Tipo", type text}}),
				    #"Removed Blank Rows" = Table.SelectRows(#"Changed Type", each not List.IsEmpty(List.RemoveMatchingItems(Record.FieldValues(_), {"", null}))),
				    #"Changed Type1" = Table.TransformColumnTypes(#"Removed Blank Rows",{{"Data Lançamento", type datetime}}),
				    #"Renamed Columns" = Table.RenameColumns(#"Changed Type1",{{"Montante (R$)", "Montante (signed)"}})
				in
				    #"Renamed Columns"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

