{
  "compatibilityLevel": 1601,
  "model": {
    "annotations": [
      {
        "name": "__PBI_TimeIntelligenceEnabled",
        "value": "1"
      },
      {
        "name": "PBI_QueryOrder",
        "value": "[\"Transações\",\"dFinalidades\",\"dSubunidades\",\"Errors in Transações\",\"pendências\"]"
      },
      {
        "name": "PBI_ProTooling",
        "value": "[\"DevMode\"]"
      }
    ],
    "culture": "en-US",
    "cultures": [
      {
        "name": "en-US",
        "linguisticMetadata": {
          "content": {
            "Agents": {
              "Internal": {
                "Version": "1.1.0"
              }
            },
            "Entities": {
              "d_calendario": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "dCalendario"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "d calendario": {
                      "State": "Generated"
                    }
                  },
                  {
                    "dCalendario": {
                      "State": "Generated",
                      "Type": "Noun",
                      "Weight": 0.99
                    }
                  }
                ]
              },
              "d_calendario.ano": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "dCalendario",
                    "ConceptualProperty": "Ano"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "ano": {
                      "State": "Generated"
                    }
                  }
                ]
              },
              "d_calendario.ano_atual": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "dCalendario",
                    "ConceptualProperty": "Ano atual"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "ano atual": {
                      "State": "Generated"
                    }
                  }
                ]
              },
              "d_calendario.date": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "dCalendario",
                    "ConceptualProperty": "Date"
                  }
                },
                "SemanticType": "Time",
                "State": "Generated",
                "Terms": [
                  {
                    "date": {
                      "State": "Generated"
                    }
                  },
                  {
                    "moment": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.736
                    }
                  },
                  {
                    "period": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.714
                    }
                  }
                ]
              },
              "d_calendario.date.date_hierarchy": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "dCalendario",
                    "Hierarchy": "Date Hierarchy",
                    "VariationSet": "Variation",
                    "VariationSource": "Date"
                  }
                },
                "SemanticType": "Time",
                "State": "Generated",
                "Terms": [
                  {
                    "date hierarchy": {
                      "State": "Generated",
                      "Weight": 0.97
                    }
                  }
                ]
              },
              "d_calendario.date.day": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "dCalendario",
                    "Hierarchy": "Date Hierarchy",
                    "HierarchyLevel": "Day",
                    "VariationSet": "Variation",
                    "VariationSource": "Date"
                  }
                },
                "SemanticType": "Time",
                "State": "Generated",
                "Terms": [
                  {
                    "day": {
                      "State": "Generated"
                    }
                  },
                  {
                    "date day": {
                      "State": "Generated"
                    }
                  },
                  {
                    "moment day": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.6
                    }
                  },
                  {
                    "period day": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.582
                    }
                  }
                ]
              },
              "d_calendario.date.month": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "dCalendario",
                    "Hierarchy": "Date Hierarchy",
                    "HierarchyLevel": "Month",
                    "VariationSet": "Variation",
                    "VariationSource": "Date"
                  }
                },
                "SemanticType": "Time",
                "State": "Generated",
                "Terms": [
                  {
                    "month": {
                      "State": "Generated"
                    }
                  },
                  {
                    "date month": {
                      "State": "Generated"
                    }
                  },
                  {
                    "date mth": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.75
                    }
                  },
                  {
                    "mth": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.736
                    }
                  },
                  {
                    "moment month": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.6
                    }
                  },
                  {
                    "period month": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.582
                    }
                  }
                ]
              },
              "d_calendario.date.quarter": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "dCalendario",
                    "Hierarchy": "Date Hierarchy",
                    "HierarchyLevel": "Quarter",
                    "VariationSet": "Variation",
                    "VariationSource": "Date"
                  }
                },
                "SemanticType": "Time",
                "State": "Generated",
                "Terms": [
                  {
                    "quarter": {
                      "State": "Generated"
                    }
                  },
                  {
                    "date quarter": {
                      "State": "Generated"
                    }
                  },
                  {
                    "date qtr": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.833
                    }
                  },
                  {
                    "qtr": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.818
                    }
                  },
                  {
                    "moment quarter": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.6
                    }
                  },
                  {
                    "period quarter": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.582
                    }
                  }
                ]
              },
              "d_calendario.date.year": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "dCalendario",
                    "Hierarchy": "Date Hierarchy",
                    "HierarchyLevel": "Year",
                    "VariationSet": "Variation",
                    "VariationSource": "Date"
                  }
                },
                "SemanticType": "Time",
                "State": "Generated",
                "Terms": [
                  {
                    "year": {
                      "State": "Generated"
                    }
                  },
                  {
                    "date year": {
                      "State": "Generated"
                    }
                  },
                  {
                    "date yr": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.75
                    }
                  },
                  {
                    "yr": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.736
                    }
                  },
                  {
                    "moment year": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.6
                    }
                  },
                  {
                    "period year": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.582
                    }
                  }
                ]
              },
              "d_calendario.dia": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "dCalendario",
                    "ConceptualProperty": "Dia"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "dia": {
                      "State": "Generated"
                    }
                  }
                ]
              },
              "d_calendario.dia_atual": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "dCalendario",
                    "ConceptualProperty": "Dia atual"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "dia atual": {
                      "State": "Generated"
                    }
                  }
                ]
              },
              "d_calendario.mês_atual": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "dCalendario",
                    "ConceptualProperty": "Mês atual"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "mês atual": {
                      "State": "Generated"
                    }
                  },
                  {
                    "mê atual": {
                      "State": "Generated",
                      "Type": "Noun",
                      "Weight": 0.78
                    }
                  }
                ]
              },
              "d_calendario.mês_nome": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "dCalendario",
                    "ConceptualProperty": "Mês nome"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "mês nome": {
                      "State": "Generated"
                    }
                  },
                  {
                    "mê nome": {
                      "State": "Generated",
                      "Type": "Noun",
                      "Weight": 0.78
                    }
                  },
                  {
                    "Mês": {
                      "Source": {
                        "Agent": "PowerBI.VisualColumnRename",
                        "Type": "External"
                      },
                      "State": "Suggested",
                      "Weight": 0.9
                    }
                  }
                ]
              },
              "d_calendario.mês_num": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "dCalendario",
                    "ConceptualProperty": "Mês num"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "mês num": {
                      "State": "Generated"
                    }
                  },
                  {
                    "mê num": {
                      "State": "Generated",
                      "Type": "Noun",
                      "Weight": 0.78
                    }
                  },
                  {
                    "mê number": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.727
                    }
                  }
                ]
              },
              "d_finalidade": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "dFinalidades"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "d finalidade": {
                      "State": "Generated"
                    }
                  },
                  {
                    "dFinalidades": {
                      "State": "Generated",
                      "Type": "Noun",
                      "Weight": 0.99
                    }
                  }
                ]
              },
              "d_finalidade.finalidade": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "dFinalidades",
                    "ConceptualProperty": "Finalidade"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "finalidade": {
                      "State": "Generated"
                    }
                  }
                ]
              },
              "d_finalidade.tipo": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "dFinalidades",
                    "ConceptualProperty": "Tipo"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "tipo": {
                      "State": "Generated"
                    }
                  }
                ]
              },
              "d_subunidade": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "dSubunidades"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "d subunidade": {
                      "State": "Generated"
                    }
                  },
                  {
                    "dSubunidades": {
                      "State": "Generated",
                      "Type": "Noun",
                      "Weight": 0.99
                    }
                  }
                ]
              },
              "d_subunidade.classificação": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "dSubunidades",
                    "ConceptualProperty": "Classificação"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "classificação": {
                      "State": "Generated"
                    }
                  }
                ]
              },
              "d_subunidade.nome": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "dSubunidades",
                    "ConceptualProperty": "Nome"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "nome": {
                      "State": "Generated"
                    }
                  }
                ]
              },
              "pendência": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "pendências"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "pendência": {
                      "State": "Generated"
                    }
                  }
                ]
              },
              "pendência.linhas_em_azul_com_dados_faltante": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "pendências",
                    "ConceptualProperty": "Linhas (em azul) com dados faltantes"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "linhas (em azul) com dados faltante": {
                      "State": "Generated"
                    }
                  },
                  {
                    "linha (em azul) com dado faltante": {
                      "State": "Generated",
                      "Type": "Noun",
                      "Weight": 0.78
                    }
                  }
                ]
              },
              "transaçõe": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "Transações"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "transaçõe": {
                      "State": "Generated"
                    }
                  }
                ]
              },
              "transaçõe.créditos_IDR": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "Transações",
                    "ConceptualProperty": "Créditos IDR"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "créditos IDR": {
                      "State": "Generated"
                    }
                  }
                ]
              },
              "transaçõe.créditos_totais": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "Transações",
                    "ConceptualProperty": "Créditos totais"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "créditos totais": {
                      "State": "Generated"
                    }
                  }
                ]
              },
              "transaçõe.créditos_transferências": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "Transações",
                    "ConceptualProperty": "Créditos transferências"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "créditos transferências": {
                      "State": "Generated"
                    }
                  }
                ]
              },
              "transaçõe.data_lançamento": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "Transações",
                    "ConceptualProperty": "Data Lançamento"
                  }
                },
                "SemanticType": "Time",
                "State": "Generated",
                "Terms": [
                  {
                    "data lançamento": {
                      "State": "Generated"
                    }
                  },
                  {
                    "date": {
                      "State": "Generated",
                      "Weight": 0.7
                    }
                  },
                  {
                    "information lançamento": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.6
                    }
                  },
                  {
                    "fact lançamento": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.6
                    }
                  },
                  {
                    "info lançamento": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.6
                    }
                  },
                  {
                    "statistic lançamento": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.6
                    }
                  },
                  {
                    "document lançamento": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.582
                    }
                  },
                  {
                    "figure lançamento": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.582
                    }
                  },
                  {
                    "record lançamento": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.582
                    }
                  },
                  {
                    "Data": {
                      "Source": {
                        "Agent": "PowerBI.VisualColumnRename",
                        "Type": "External"
                      },
                      "State": "Suggested",
                      "Weight": 0.9
                    }
                  }
                ]
              },
              "transaçõe.descrição__beneficiário": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "Transações",
                    "ConceptualProperty": "Descrição + Beneficiário"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "descrição + beneficiário": {
                      "State": "Generated"
                    }
                  },
                  {
                    "Descrição": {
                      "Source": {
                        "Agent": "PowerBI.VisualColumnRename",
                        "Type": "External"
                      },
                      "State": "Suggested",
                      "Weight": 0.9
                    }
                  }
                ]
              },
              "transaçõe.doc_de_pagamento": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "Transações",
                    "ConceptualProperty": "Doc de Pagamento"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "doc de pagamento": {
                      "State": "Generated"
                    }
                  }
                ]
              },
              "transaçõe.doc_de_solitação": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "Transações",
                    "ConceptualProperty": "Doc de Solitação"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "doc de solitação": {
                      "State": "Generated"
                    }
                  }
                ]
              },
              "transaçõe.débitos_totais": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "Transações",
                    "ConceptualProperty": "Débitos totais"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "débitos totais": {
                      "State": "Generated"
                    }
                  }
                ]
              },
              "transaçõe.débitos_totais_a_pagar": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "Transações",
                    "ConceptualProperty": "Débitos totais a pagar"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "débitos totais a pagar": {
                      "State": "Generated"
                    }
                  }
                ]
              },
              "transaçõe.débitos_totais_pagos": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "Transações",
                    "ConceptualProperty": "Débitos totais pagos"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "débitos totais pagos": {
                      "State": "Generated"
                    }
                  }
                ]
              },
              "transaçõe.débitos_transferências": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "Transações",
                    "ConceptualProperty": "Débitos transferências"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "débitos transferências": {
                      "State": "Generated"
                    }
                  }
                ]
              },
              "transaçõe.empenho_SIAFI": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "Transações",
                    "ConceptualProperty": "Empenho SIAFI"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "empenho SIAFI": {
                      "State": "Generated"
                    }
                  }
                ]
              },
              "transaçõe.empenho_SIE": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "Transações",
                    "ConceptualProperty": "Empenho SIE"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "empenho SIE": {
                      "State": "Generated"
                    }
                  }
                ]
              },
              "transaçõe.finalidade": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "Transações",
                    "ConceptualProperty": "Finalidade"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "finalidade": {
                      "State": "Generated"
                    }
                  }
                ],
                "Visibility": {
                  "Value": "Hidden"
                }
              },
              "transaçõe.finalidade_detalhada": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "Transações",
                    "ConceptualProperty": "Finalidade (detalhada)"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "finalidade (detalhada)": {
                      "State": "Generated"
                    }
                  },
                  {
                    "finalidade": {
                      "State": "Generated",
                      "Weight": 0.75
                    }
                  }
                ]
              },
              "transaçõe.linha": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "Transações",
                    "ConceptualProperty": "Linha"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "linha": {
                      "State": "Generated"
                    }
                  }
                ],
                "Visibility": {
                  "Value": "Hidden"
                }
              },
              "transaçõe.lista_SIAFI": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "Transações",
                    "ConceptualProperty": "Lista SIAFI"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "lista SIAFI": {
                      "State": "Generated"
                    }
                  }
                ]
              },
              "transaçõe.local___trecho": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "Transações",
                    "ConceptualProperty": "Local / Trecho"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "local / trecho": {
                      "State": "Generated"
                    }
                  },
                  {
                    "local": {
                      "State": "Generated",
                      "Weight": 0.97
                    }
                  },
                  {
                    "local trecho": {
                      "State": "Generated",
                      "Weight": 0.97
                    }
                  },
                  {
                    "trecho": {
                      "State": "Generated",
                      "Weight": 0.97
                    }
                  },
                  {
                    "native": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.476
                    }
                  },
                  {
                    "resident": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.476
                    }
                  },
                  {
                    "home-grown": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.476
                    }
                  },
                  {
                    "narrow": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.452
                    }
                  }
                ]
              },
              "transaçõe.montante": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "Transações",
                    "ConceptualProperty": "Montante"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "montante": {
                      "State": "Generated"
                    }
                  }
                ]
              },
              "transaçõe.pago": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "Transações",
                    "ConceptualProperty": "Pago"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "pago": {
                      "State": "Generated"
                    }
                  }
                ]
              },
              "transaçõe.quantidade": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "Transações",
                    "ConceptualProperty": "Quantidade"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "quantidade": {
                      "State": "Generated"
                    }
                  }
                ]
              },
              "transaçõe.subunidade": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "Transações",
                    "ConceptualProperty": "Subunidade"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "subunidade": {
                      "State": "Generated"
                    }
                  }
                ],
                "Visibility": {
                  "Value": "Hidden"
                }
              },
              "transaçõe.tipo": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "Transações",
                    "ConceptualProperty": "Tipo"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "tipo": {
                      "State": "Generated"
                    }
                  }
                ]
              },
              "transaçõe.tipo_subunidade": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "Transações",
                    "ConceptualProperty": "Tipo subunidade"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "tipo subunidade": {
                      "State": "Generated"
                    }
                  }
                ]
              }
            },
            "Language": "en-US",
            "Relationships": {
              "d_calendario_date_date_hierarchy_has_d_calendario_date_day": {
                "Binding": {
                  "ConceptualEntity": "dCalendario"
                },
                "Phrasings": [
                  {
                    "Attribute": {
                      "Object": {
                        "Role": "d_calendario.date.day"
                      },
                      "Subject": {
                        "Role": "d_calendario.date.date_hierarchy"
                      }
                    },
                    "ID": "date_hierarchies_have_days",
                    "State": "Generated",
                    "Weight": 0.99
                  }
                ],
                "Roles": {
                  "d_calendario.date.date_hierarchy": {
                    "Target": {
                      "Entity": "d_calendario.date.date_hierarchy"
                    }
                  },
                  "d_calendario.date.day": {
                    "Target": {
                      "Entity": "d_calendario.date.day"
                    }
                  }
                },
                "State": "Generated"
              },
              "d_calendario_date_date_hierarchy_has_d_calendario_date_month": {
                "Binding": {
                  "ConceptualEntity": "dCalendario"
                },
                "Phrasings": [
                  {
                    "Attribute": {
                      "Object": {
                        "Role": "d_calendario.date.month"
                      },
                      "Subject": {
                        "Role": "d_calendario.date.date_hierarchy"
                      }
                    },
                    "ID": "date_hierarchies_have_months",
                    "State": "Generated",
                    "Weight": 0.99
                  }
                ],
                "Roles": {
                  "d_calendario.date.date_hierarchy": {
                    "Target": {
                      "Entity": "d_calendario.date.date_hierarchy"
                    }
                  },
                  "d_calendario.date.month": {
                    "Target": {
                      "Entity": "d_calendario.date.month"
                    }
                  }
                },
                "State": "Generated"
              },
              "d_calendario_date_date_hierarchy_has_d_calendario_date_quarter": {
                "Binding": {
                  "ConceptualEntity": "dCalendario"
                },
                "Phrasings": [
                  {
                    "Attribute": {
                      "Object": {
                        "Role": "d_calendario.date.quarter"
                      },
                      "Subject": {
                        "Role": "d_calendario.date.date_hierarchy"
                      }
                    },
                    "ID": "date_hierarchies_have_quarters",
                    "State": "Generated",
                    "Weight": 0.99
                  }
                ],
                "Roles": {
                  "d_calendario.date.date_hierarchy": {
                    "Target": {
                      "Entity": "d_calendario.date.date_hierarchy"
                    }
                  },
                  "d_calendario.date.quarter": {
                    "Target": {
                      "Entity": "d_calendario.date.quarter"
                    }
                  }
                },
                "State": "Generated"
              },
              "d_calendario_date_date_hierarchy_has_d_calendario_date_year": {
                "Binding": {
                  "ConceptualEntity": "dCalendario"
                },
                "Phrasings": [
                  {
                    "Attribute": {
                      "Object": {
                        "Role": "d_calendario.date.year"
                      },
                      "Subject": {
                        "Role": "d_calendario.date.date_hierarchy"
                      }
                    },
                    "ID": "date_hierarchies_have_years",
                    "State": "Generated",
                    "Weight": 0.99
                  }
                ],
                "Roles": {
                  "d_calendario.date.date_hierarchy": {
                    "Target": {
                      "Entity": "d_calendario.date.date_hierarchy"
                    }
                  },
                  "d_calendario.date.year": {
                    "Target": {
                      "Entity": "d_calendario.date.year"
                    }
                  }
                },
                "State": "Generated"
              },
              "d_calendario_date_has_date_hierarchy": {
                "Binding": {
                  "ConceptualEntity": "dCalendario"
                },
                "Phrasings": [
                  {
                    "Attribute": {
                      "Object": {
                        "Role": "d_calendario.date.date_hierarchy"
                      },
                      "Subject": {
                        "Role": "d_calendario.date"
                      }
                    },
                    "ID": "dates_have_date_hierarchies",
                    "State": "Generated",
                    "Weight": 0.99
                  }
                ],
                "Roles": {
                  "d_calendario.date": {
                    "Target": {
                      "Entity": "d_calendario.date"
                    }
                  },
                  "d_calendario.date.date_hierarchy": {
                    "Target": {
                      "Entity": "d_calendario.date.date_hierarchy"
                    }
                  }
                },
                "State": "Generated"
              },
              "d_calendario_has_ano": {
                "Binding": {
                  "ConceptualEntity": "dCalendario"
                },
                "Phrasings": [
                  {
                    "Attribute": {
                      "Object": {
                        "Role": "d_calendario.ano"
                      },
                      "Subject": {
                        "Role": "d_calendario"
                      }
                    },
                    "ID": "d_calendarios_have_anos",
                    "State": "Generated",
                    "Weight": 0.99
                  }
                ],
                "Roles": {
                  "d_calendario": {
                    "Target": {
                      "Entity": "d_calendario"
                    }
                  },
                  "d_calendario.ano": {
                    "Target": {
                      "Entity": "d_calendario.ano"
                    }
                  }
                },
                "State": "Generated"
              },
              "d_calendario_has_ano_atual": {
                "Binding": {
                  "ConceptualEntity": "dCalendario"
                },
                "Phrasings": [
                  {
                    "Attribute": {
                      "Object": {
                        "Role": "d_calendario.ano_atual"
                      },
                      "Subject": {
                        "Role": "d_calendario"
                      }
                    },
                    "ID": "d_calendarios_have_ano_atuals",
                    "State": "Generated",
                    "Weight": 0.99
                  }
                ],
                "Roles": {
                  "d_calendario": {
                    "Target": {
                      "Entity": "d_calendario"
                    }
                  },
                  "d_calendario.ano_atual": {
                    "Target": {
                      "Entity": "d_calendario.ano_atual"
                    }
                  }
                },
                "State": "Generated"
              },
              "d_calendario_has_date": {
                "Binding": {
                  "ConceptualEntity": "dCalendario"
                },
                "Phrasings": [
                  {
                    "Attribute": {
                      "Object": {
                        "Role": "d_calendario.date"
                      },
                      "Subject": {
                        "Role": "d_calendario"
                      }
                    },
                    "ID": "d_calendarios_have_dates",
                    "State": "Generated",
                    "Weight": 0.99
                  }
                ],
                "Roles": {
                  "d_calendario": {
                    "Target": {
                      "Entity": "d_calendario"
                    }
                  },
                  "d_calendario.date": {
                    "Target": {
                      "Entity": "d_calendario.date"
                    }
                  }
                },
                "State": "Generated"
              },
              "d_calendario_has_dia": {
                "Binding": {
                  "ConceptualEntity": "dCalendario"
                },
                "Phrasings": [
                  {
                    "Attribute": {
                      "Object": {
                        "Role": "d_calendario.dia"
                      },
                      "Subject": {
                        "Role": "d_calendario"
                      }
                    },
                    "ID": "d_calendarios_have_dias",
                    "State": "Generated",
                    "Weight": 0.99
                  }
                ],
                "Roles": {
                  "d_calendario": {
                    "Target": {
                      "Entity": "d_calendario"
                    }
                  },
                  "d_calendario.dia": {
                    "Target": {
                      "Entity": "d_calendario.dia"
                    }
                  }
                },
                "State": "Generated"
              },
              "d_calendario_has_dia_atual": {
                "Binding": {
                  "ConceptualEntity": "dCalendario"
                },
                "Phrasings": [
                  {
                    "Attribute": {
                      "Object": {
                        "Role": "d_calendario.dia_atual"
                      },
                      "Subject": {
                        "Role": "d_calendario"
                      }
                    },
                    "ID": "d_calendarios_have_dia_atuals",
                    "State": "Generated",
                    "Weight": 0.99
                  }
                ],
                "Roles": {
                  "d_calendario": {
                    "Target": {
                      "Entity": "d_calendario"
                    }
                  },
                  "d_calendario.dia_atual": {
                    "Target": {
                      "Entity": "d_calendario.dia_atual"
                    }
                  }
                },
                "State": "Generated"
              },
              "d_calendario_has_mês_atual": {
                "Binding": {
                  "ConceptualEntity": "dCalendario"
                },
                "Phrasings": [
                  {
                    "Attribute": {
                      "Object": {
                        "Role": "d_calendario.mês_atual"
                      },
                      "Subject": {
                        "Role": "d_calendario"
                      }
                    },
                    "ID": "d_calendarios_have_mês_atuals",
                    "State": "Generated",
                    "Weight": 0.99
                  }
                ],
                "Roles": {
                  "d_calendario": {
                    "Target": {
                      "Entity": "d_calendario"
                    }
                  },
                  "d_calendario.mês_atual": {
                    "Target": {
                      "Entity": "d_calendario.mês_atual"
                    }
                  }
                },
                "State": "Generated"
              },
              "d_calendario_has_mês_nome": {
                "Binding": {
                  "ConceptualEntity": "dCalendario"
                },
                "Phrasings": [
                  {
                    "Attribute": {
                      "Object": {
                        "Role": "d_calendario.mês_nome"
                      },
                      "Subject": {
                        "Role": "d_calendario"
                      }
                    },
                    "ID": "d_calendarios_have_mês_nome",
                    "State": "Generated",
                    "Weight": 0.99
                  }
                ],
                "Roles": {
                  "d_calendario": {
                    "Target": {
                      "Entity": "d_calendario"
                    }
                  },
                  "d_calendario.mês_nome": {
                    "Target": {
                      "Entity": "d_calendario.mês_nome"
                    }
                  }
                },
                "State": "Generated"
              },
              "d_calendario_has_mês_num": {
                "Binding": {
                  "ConceptualEntity": "dCalendario"
                },
                "Phrasings": [
                  {
                    "Attribute": {
                      "Object": {
                        "Role": "d_calendario.mês_num"
                      },
                      "Subject": {
                        "Role": "d_calendario"
                      }
                    },
                    "ID": "d_calendarios_have_mês_nums",
                    "State": "Generated",
                    "Weight": 0.99
                  }
                ],
                "Roles": {
                  "d_calendario": {
                    "Target": {
                      "Entity": "d_calendario"
                    }
                  },
                  "d_calendario.mês_num": {
                    "Target": {
                      "Entity": "d_calendario.mês_num"
                    }
                  }
                },
                "State": "Generated"
              },
              "d_finalidade_has_finalidade": {
                "Binding": {
                  "ConceptualEntity": "dFinalidades"
                },
                "Phrasings": [
                  {
                    "Attribute": {
                      "Object": {
                        "Role": "d_finalidade.finalidade"
                      },
                      "Subject": {
                        "Role": "d_finalidade"
                      }
                    },
                    "ID": "d_finalidades_have_finalidades",
                    "State": "Generated",
                    "Weight": 0.99
                  }
                ],
                "Roles": {
                  "d_finalidade": {
                    "Target": {
                      "Entity": "d_finalidade"
                    }
                  },
                  "d_finalidade.finalidade": {
                    "Target": {
                      "Entity": "d_finalidade.finalidade"
                    }
                  }
                },
                "State": "Generated"
              },
              "d_finalidade_has_tipo": {
                "Binding": {
                  "ConceptualEntity": "dFinalidades"
                },
                "Phrasings": [
                  {
                    "Attribute": {
                      "Object": {
                        "Role": "d_finalidade.tipo"
                      },
                      "Subject": {
                        "Role": "d_finalidade"
                      }
                    },
                    "ID": "d_finalidades_have_tipos",
                    "State": "Generated",
                    "Weight": 0.99
                  }
                ],
                "Roles": {
                  "d_finalidade": {
                    "Target": {
                      "Entity": "d_finalidade"
                    }
                  },
                  "d_finalidade.tipo": {
                    "Target": {
                      "Entity": "d_finalidade.tipo"
                    }
                  }
                },
                "State": "Generated"
              },
              "d_subunidade_has_classificação": {
                "Binding": {
                  "ConceptualEntity": "dSubunidades"
                },
                "Phrasings": [
                  {
                    "Attribute": {
                      "Object": {
                        "Role": "d_subunidade.classificação"
                      },
                      "Subject": {
                        "Role": "d_subunidade"
                      }
                    },
                    "ID": "d_subunidades_have_classificaçãos",
                    "State": "Generated",
                    "Weight": 0.99
                  }
                ],
                "Roles": {
                  "d_subunidade": {
                    "Target": {
                      "Entity": "d_subunidade"
                    }
                  },
                  "d_subunidade.classificação": {
                    "Target": {
                      "Entity": "d_subunidade.classificação"
                    }
                  }
                },
                "State": "Generated"
              },
              "d_subunidade_has_nome": {
                "Binding": {
                  "ConceptualEntity": "dSubunidades"
                },
                "Phrasings": [
                  {
                    "Attribute": {
                      "Object": {
                        "Role": "d_subunidade.nome"
                      },
                      "Subject": {
                        "Role": "d_subunidade"
                      }
                    },
                    "ID": "d_subunidades_have_nome",
                    "State": "Generated",
                    "Weight": 0.99
                  }
                ],
                "Roles": {
                  "d_subunidade": {
                    "Target": {
                      "Entity": "d_subunidade"
                    }
                  },
                  "d_subunidade.nome": {
                    "Target": {
                      "Entity": "d_subunidade.nome"
                    }
                  }
                },
                "State": "Generated"
              },
              "pendência_has_linhas_em_azul_com_dados_faltante": {
                "Binding": {
                  "ConceptualEntity": "pendências"
                },
                "Phrasings": [
                  {
                    "Attribute": {
                      "Object": {
                        "Role": "pendência.linhas_em_azul_com_dados_faltante"
                      },
                      "Subject": {
                        "Role": "pendência"
                      }
                    },
                    "ID": "pendências_have_linhas_em_azul_com_dados_faltantes",
                    "State": "Generated",
                    "Weight": 0.99
                  }
                ],
                "Roles": {
                  "pendência": {
                    "Target": {
                      "Entity": "pendência"
                    }
                  },
                  "pendência.linhas_em_azul_com_dados_faltante": {
                    "Target": {
                      "Entity": "pendência.linhas_em_azul_com_dados_faltante"
                    }
                  }
                },
                "State": "Generated"
              },
              "transaçõe_has_créditos_IDR": {
                "Binding": {
                  "ConceptualEntity": "Transações"
                },
                "Phrasings": [
                  {
                    "Attribute": {
                      "Object": {
                        "Role": "transaçõe.créditos_IDR"
                      },
                      "Subject": {
                        "Role": "transaçõe"
                      }
                    },
                    "ID": "transações_have_créditos_IDR",
                    "State": "Generated",
                    "Weight": 0.99
                  }
                ],
                "Roles": {
                  "transaçõe": {
                    "Target": {
                      "Entity": "transaçõe"
                    }
                  },
                  "transaçõe.créditos_IDR": {
                    "Target": {
                      "Entity": "transaçõe.créditos_IDR"
                    }
                  }
                },
                "State": "Generated"
              },
              "transaçõe_has_créditos_totais": {
                "Binding": {
                  "ConceptualEntity": "Transações"
                },
                "Phrasings": [
                  {
                    "Attribute": {
                      "Object": {
                        "Role": "transaçõe.créditos_totais"
                      },
                      "Subject": {
                        "Role": "transaçõe"
                      }
                    },
                    "ID": "transações_have_créditos_totais",
                    "State": "Generated",
                    "Weight": 0.99
                  }
                ],
                "Roles": {
                  "transaçõe": {
                    "Target": {
                      "Entity": "transaçõe"
                    }
                  },
                  "transaçõe.créditos_totais": {
                    "Target": {
                      "Entity": "transaçõe.créditos_totais"
                    }
                  }
                },
                "State": "Generated"
              },
              "transaçõe_has_créditos_transferências": {
                "Binding": {
                  "ConceptualEntity": "Transações"
                },
                "Phrasings": [
                  {
                    "Attribute": {
                      "Object": {
                        "Role": "transaçõe.créditos_transferências"
                      },
                      "Subject": {
                        "Role": "transaçõe"
                      }
                    },
                    "ID": "transações_have_créditos_transferências",
                    "State": "Generated",
                    "Weight": 0.99
                  }
                ],
                "Roles": {
                  "transaçõe": {
                    "Target": {
                      "Entity": "transaçõe"
                    }
                  },
                  "transaçõe.créditos_transferências": {
                    "Target": {
                      "Entity": "transaçõe.créditos_transferências"
                    }
                  }
                },
                "State": "Generated"
              },
              "transaçõe_has_d_calendario": {
                "Binding": {
                  "ConceptualEntity": "Transações"
                },
                "Phrasings": [
                  {
                    "Attribute": {
                      "Object": {
                        "Role": "d_calendario"
                      },
                      "Subject": {
                        "Role": "transaçõe"
                      }
                    },
                    "ID": "transações_have_d_calendarios",
                    "State": "Generated",
                    "Weight": 0.99
                  },
                  {
                    "Attribute": {
                      "Object": {
                        "Role": "transaçõe"
                      },
                      "Subject": {
                        "Role": "d_calendario"
                      }
                    },
                    "ID": "d_calendarios_have_transações",
                    "State": "Generated",
                    "Weight": 0.99
                  }
                ],
                "Roles": {
                  "d_calendario": {
                    "Nouns": [
                      {
                        "Data": {
                          "State": "Generated"
                        }
                      }
                    ],
                    "Target": {
                      "Entity": "d_calendario"
                    }
                  },
                  "transaçõe": {
                    "Target": {
                      "Entity": "transaçõe"
                    }
                  }
                },
                "State": "Generated"
              },
              "transaçõe_has_d_finalidade": {
                "Binding": {
                  "ConceptualEntity": "Transações"
                },
                "Phrasings": [
                  {
                    "Attribute": {
                      "Object": {
                        "Role": "d_finalidade"
                      },
                      "Subject": {
                        "Role": "transaçõe"
                      }
                    },
                    "ID": "transações_have_d_finalidades",
                    "State": "Generated",
                    "Weight": 0.99
                  },
                  {
                    "Attribute": {
                      "Object": {
                        "Role": "transaçõe"
                      },
                      "Subject": {
                        "Role": "d_finalidade"
                      }
                    },
                    "ID": "d_finalidades_have_transações",
                    "State": "Generated",
                    "Weight": 0.99
                  }
                ],
                "Roles": {
                  "d_finalidade": {
                    "Target": {
                      "Entity": "d_finalidade"
                    }
                  },
                  "transaçõe": {
                    "Target": {
                      "Entity": "transaçõe"
                    }
                  }
                },
                "State": "Generated"
              },
              "transaçõe_has_d_subunidade": {
                "Binding": {
                  "ConceptualEntity": "Transações"
                },
                "Phrasings": [
                  {
                    "Attribute": {
                      "Object": {
                        "Role": "d_subunidade"
                      },
                      "Subject": {
                        "Role": "transaçõe"
                      }
                    },
                    "ID": "transações_have_d_subunidades",
                    "State": "Generated",
                    "Weight": 0.99
                  },
                  {
                    "Attribute": {
                      "Object": {
                        "Role": "transaçõe"
                      },
                      "Subject": {
                        "Role": "d_subunidade"
                      }
                    },
                    "ID": "d_subunidades_have_transações",
                    "State": "Generated",
                    "Weight": 0.99
                  }
                ],
                "Roles": {
                  "d_subunidade": {
                    "Target": {
                      "Entity": "d_subunidade"
                    }
                  },
                  "transaçõe": {
                    "Target": {
                      "Entity": "transaçõe"
                    }
                  }
                },
                "State": "Generated"
              },
              "transaçõe_has_data_lançamento": {
                "Binding": {
                  "ConceptualEntity": "Transações"
                },
                "Phrasings": [
                  {
                    "Attribute": {
                      "Object": {
                        "Role": "transaçõe.data_lançamento"
                      },
                      "Subject": {
                        "Role": "transaçõe"
                      }
                    },
                    "ID": "transações_have_data_lançamentos",
                    "State": "Generated",
                    "Weight": 0.99
                  }
                ],
                "Roles": {
                  "transaçõe": {
                    "Target": {
                      "Entity": "transaçõe"
                    }
                  },
                  "transaçõe.data_lançamento": {
                    "Target": {
                      "Entity": "transaçõe.data_lançamento"
                    }
                  }
                },
                "State": "Generated"
              },
              "transaçõe_has_descrição__beneficiário": {
                "Binding": {
                  "ConceptualEntity": "Transações"
                },
                "Phrasings": [
                  {
                    "Attribute": {
                      "Object": {
                        "Role": "transaçõe.descrição__beneficiário"
                      },
                      "Subject": {
                        "Role": "transaçõe"
                      }
                    },
                    "ID": "transações_have_descrição__beneficiários",
                    "State": "Generated",
                    "Weight": 0.99
                  }
                ],
                "Roles": {
                  "transaçõe": {
                    "Target": {
                      "Entity": "transaçõe"
                    }
                  },
                  "transaçõe.descrição__beneficiário": {
                    "Target": {
                      "Entity": "transaçõe.descrição__beneficiário"
                    }
                  }
                },
                "State": "Generated"
              },
              "transaçõe_has_doc_de_pagamento": {
                "Binding": {
                  "ConceptualEntity": "Transações"
                },
                "Phrasings": [
                  {
                    "Attribute": {
                      "Object": {
                        "Role": "transaçõe.doc_de_pagamento"
                      },
                      "Subject": {
                        "Role": "transaçõe"
                      }
                    },
                    "ID": "transações_have_doc_de_pagamentos",
                    "State": "Generated",
                    "Weight": 0.99
                  }
                ],
                "Roles": {
                  "transaçõe": {
                    "Target": {
                      "Entity": "transaçõe"
                    }
                  },
                  "transaçõe.doc_de_pagamento": {
                    "Target": {
                      "Entity": "transaçõe.doc_de_pagamento"
                    }
                  }
                },
                "State": "Generated"
              },
              "transaçõe_has_doc_de_solitação": {
                "Binding": {
                  "ConceptualEntity": "Transações"
                },
                "Phrasings": [
                  {
                    "Attribute": {
                      "Object": {
                        "Role": "transaçõe.doc_de_solitação"
                      },
                      "Subject": {
                        "Role": "transaçõe"
                      }
                    },
                    "ID": "transações_have_doc_de_solitaçãos",
                    "State": "Generated",
                    "Weight": 0.99
                  }
                ],
                "Roles": {
                  "transaçõe": {
                    "Target": {
                      "Entity": "transaçõe"
                    }
                  },
                  "transaçõe.doc_de_solitação": {
                    "Target": {
                      "Entity": "transaçõe.doc_de_solitação"
                    }
                  }
                },
                "State": "Generated"
              },
              "transaçõe_has_débitos_totais": {
                "Binding": {
                  "ConceptualEntity": "Transações"
                },
                "Phrasings": [
                  {
                    "Attribute": {
                      "Object": {
                        "Role": "transaçõe.débitos_totais"
                      },
                      "Subject": {
                        "Role": "transaçõe"
                      }
                    },
                    "ID": "transações_have_débitos_totais",
                    "State": "Generated",
                    "Weight": 0.99
                  }
                ],
                "Roles": {
                  "transaçõe": {
                    "Target": {
                      "Entity": "transaçõe"
                    }
                  },
                  "transaçõe.débitos_totais": {
                    "Target": {
                      "Entity": "transaçõe.débitos_totais"
                    }
                  }
                },
                "State": "Generated"
              },
              "transaçõe_has_débitos_totais_a_pagar": {
                "Binding": {
                  "ConceptualEntity": "Transações"
                },
                "Phrasings": [
                  {
                    "Attribute": {
                      "Object": {
                        "Role": "transaçõe.débitos_totais_a_pagar"
                      },
                      "Subject": {
                        "Role": "transaçõe"
                      }
                    },
                    "ID": "transações_have_débitos_totais_a_pagar",
                    "State": "Generated",
                    "Weight": 0.99
                  }
                ],
                "Roles": {
                  "transaçõe": {
                    "Target": {
                      "Entity": "transaçõe"
                    }
                  },
                  "transaçõe.débitos_totais_a_pagar": {
                    "Target": {
                      "Entity": "transaçõe.débitos_totais_a_pagar"
                    }
                  }
                },
                "State": "Generated"
              },
              "transaçõe_has_débitos_totais_pagos": {
                "Binding": {
                  "ConceptualEntity": "Transações"
                },
                "Phrasings": [
                  {
                    "Attribute": {
                      "Object": {
                        "Role": "transaçõe.débitos_totais_pagos"
                      },
                      "Subject": {
                        "Role": "transaçõe"
                      }
                    },
                    "ID": "transações_have_débitos_totais_pagos",
                    "State": "Generated",
                    "Weight": 0.99
                  }
                ],
                "Roles": {
                  "transaçõe": {
                    "Target": {
                      "Entity": "transaçõe"
                    }
                  },
                  "transaçõe.débitos_totais_pagos": {
                    "Target": {
                      "Entity": "transaçõe.débitos_totais_pagos"
                    }
                  }
                },
                "State": "Generated"
              },
              "transaçõe_has_débitos_transferências": {
                "Binding": {
                  "ConceptualEntity": "Transações"
                },
                "Phrasings": [
                  {
                    "Attribute": {
                      "Object": {
                        "Role": "transaçõe.débitos_transferências"
                      },
                      "Subject": {
                        "Role": "transaçõe"
                      }
                    },
                    "ID": "transações_have_débitos_transferências",
                    "State": "Generated",
                    "Weight": 0.99
                  }
                ],
                "Roles": {
                  "transaçõe": {
                    "Target": {
                      "Entity": "transaçõe"
                    }
                  },
                  "transaçõe.débitos_transferências": {
                    "Target": {
                      "Entity": "transaçõe.débitos_transferências"
                    }
                  }
                },
                "State": "Generated"
              },
              "transaçõe_has_empenho_SIAFI": {
                "Binding": {
                  "ConceptualEntity": "Transações"
                },
                "Phrasings": [
                  {
                    "Attribute": {
                      "Object": {
                        "Role": "transaçõe.empenho_SIAFI"
                      },
                      "Subject": {
                        "Role": "transaçõe"
                      }
                    },
                    "ID": "transações_have_empenho_SIAFIs",
                    "State": "Generated",
                    "Weight": 0.99
                  }
                ],
                "Roles": {
                  "transaçõe": {
                    "Target": {
                      "Entity": "transaçõe"
                    }
                  },
                  "transaçõe.empenho_SIAFI": {
                    "Target": {
                      "Entity": "transaçõe.empenho_SIAFI"
                    }
                  }
                },
                "State": "Generated"
              },
              "transaçõe_has_empenho_SIE": {
                "Binding": {
                  "ConceptualEntity": "Transações"
                },
                "Phrasings": [
                  {
                    "Attribute": {
                      "Object": {
                        "Role": "transaçõe.empenho_SIE"
                      },
                      "Subject": {
                        "Role": "transaçõe"
                      }
                    },
                    "ID": "transações_have_empenho_SIEs",
                    "State": "Generated",
                    "Weight": 0.99
                  }
                ],
                "Roles": {
                  "transaçõe": {
                    "Target": {
                      "Entity": "transaçõe"
                    }
                  },
                  "transaçõe.empenho_SIE": {
                    "Target": {
                      "Entity": "transaçõe.empenho_SIE"
                    }
                  }
                },
                "State": "Generated"
              },
              "transaçõe_has_finalidade_detalhada": {
                "Binding": {
                  "ConceptualEntity": "Transações"
                },
                "Phrasings": [
                  {
                    "Attribute": {
                      "Object": {
                        "Role": "transaçõe.finalidade_detalhada"
                      },
                      "Subject": {
                        "Role": "transaçõe"
                      }
                    },
                    "ID": "transações_have_finalidade_detalhada",
                    "State": "Generated",
                    "Weight": 0.99
                  }
                ],
                "Roles": {
                  "transaçõe": {
                    "Target": {
                      "Entity": "transaçõe"
                    }
                  },
                  "transaçõe.finalidade_detalhada": {
                    "Target": {
                      "Entity": "transaçõe.finalidade_detalhada"
                    }
                  }
                },
                "State": "Generated"
              },
              "transaçõe_has_lista_SIAFI": {
                "Binding": {
                  "ConceptualEntity": "Transações"
                },
                "Phrasings": [
                  {
                    "Attribute": {
                      "Object": {
                        "Role": "transaçõe.lista_SIAFI"
                      },
                      "Subject": {
                        "Role": "transaçõe"
                      }
                    },
                    "ID": "transações_have_lista_SIAFIs",
                    "State": "Generated",
                    "Weight": 0.99
                  }
                ],
                "Roles": {
                  "transaçõe": {
                    "Target": {
                      "Entity": "transaçõe"
                    }
                  },
                  "transaçõe.lista_SIAFI": {
                    "Target": {
                      "Entity": "transaçõe.lista_SIAFI"
                    }
                  }
                },
                "State": "Generated"
              },
              "transaçõe_has_local___trecho": {
                "Binding": {
                  "ConceptualEntity": "Transações"
                },
                "Phrasings": [
                  {
                    "Attribute": {
                      "Object": {
                        "Role": "transaçõe.local___trecho"
                      },
                      "Subject": {
                        "Role": "transaçõe"
                      }
                    },
                    "ID": "transações_have_local___trechos",
                    "State": "Generated",
                    "Weight": 0.99
                  }
                ],
                "Roles": {
                  "transaçõe": {
                    "Target": {
                      "Entity": "transaçõe"
                    }
                  },
                  "transaçõe.local___trecho": {
                    "Target": {
                      "Entity": "transaçõe.local___trecho"
                    }
                  }
                },
                "State": "Generated"
              },
              "transaçõe_has_montante": {
                "Binding": {
                  "ConceptualEntity": "Transações"
                },
                "Phrasings": [
                  {
                    "Attribute": {
                      "Object": {
                        "Role": "transaçõe.montante"
                      },
                      "Subject": {
                        "Role": "transaçõe"
                      }
                    },
                    "ID": "transações_have_montantes",
                    "State": "Generated",
                    "Weight": 0.99
                  },
                  {
                    "Adjective": {
                      "Adjectives": [
                        {
                          "expensive": {
                            "State": "Generated"
                          }
                        }
                      ],
                      "Antonyms": [
                        {
                          "cheap": {
                            "State": "Generated"
                          }
                        }
                      ],
                      "Measurement": {
                        "Role": "transaçõe.montante"
                      },
                      "Subject": {
                        "Role": "transaçõe"
                      }
                    },
                    "ID": "montante_indicates_how_expensive_transações_are",
                    "State": "Generated",
                    "Weight": 0.99
                  }
                ],
                "Roles": {
                  "transaçõe": {
                    "Target": {
                      "Entity": "transaçõe"
                    }
                  },
                  "transaçõe.montante": {
                    "Target": {
                      "Entity": "transaçõe.montante"
                    }
                  }
                },
                "State": "Generated"
              },
              "transaçõe_has_pago": {
                "Binding": {
                  "ConceptualEntity": "Transações"
                },
                "Phrasings": [
                  {
                    "Attribute": {
                      "Object": {
                        "Role": "transaçõe.pago"
                      },
                      "Subject": {
                        "Role": "transaçõe"
                      }
                    },
                    "ID": "transações_have_pago",
                    "State": "Generated",
                    "Weight": 0.99
                  }
                ],
                "Roles": {
                  "transaçõe": {
                    "Target": {
                      "Entity": "transaçõe"
                    }
                  },
                  "transaçõe.pago": {
                    "Target": {
                      "Entity": "transaçõe.pago"
                    }
                  }
                },
                "State": "Generated"
              },
              "transaçõe_has_pendência": {
                "Binding": {
                  "ConceptualEntity": "Transações"
                },
                "Phrasings": [
                  {
                    "Attribute": {
                      "Object": {
                        "Role": "pendência"
                      },
                      "Subject": {
                        "Role": "transaçõe"
                      }
                    },
                    "ID": "transações_have_pendências",
                    "State": "Generated",
                    "Weight": 0.99
                  },
                  {
                    "Attribute": {
                      "Object": {
                        "Role": "transaçõe"
                      },
                      "Subject": {
                        "Role": "pendência"
                      }
                    },
                    "ID": "pendências_have_transações",
                    "State": "Generated",
                    "Weight": 0.99
                  }
                ],
                "Roles": {
                  "pendência": {
                    "Target": {
                      "Entity": "pendência"
                    }
                  },
                  "transaçõe": {
                    "Target": {
                      "Entity": "transaçõe"
                    }
                  }
                },
                "State": "Generated"
              },
              "transaçõe_has_quantidade": {
                "Binding": {
                  "ConceptualEntity": "Transações"
                },
                "Phrasings": [
                  {
                    "Attribute": {
                      "Object": {
                        "Role": "transaçõe.quantidade"
                      },
                      "Subject": {
                        "Role": "transaçõe"
                      }
                    },
                    "ID": "transações_have_quantidades",
                    "State": "Generated",
                    "Weight": 0.99
                  }
                ],
                "Roles": {
                  "transaçõe": {
                    "Target": {
                      "Entity": "transaçõe"
                    }
                  },
                  "transaçõe.quantidade": {
                    "Target": {
                      "Entity": "transaçõe.quantidade"
                    }
                  }
                },
                "State": "Generated"
              },
              "transaçõe_has_tipo": {
                "Binding": {
                  "ConceptualEntity": "Transações"
                },
                "Phrasings": [
                  {
                    "Attribute": {
                      "Object": {
                        "Role": "transaçõe.tipo"
                      },
                      "Subject": {
                        "Role": "transaçõe"
                      }
                    },
                    "ID": "transações_have_tipos",
                    "State": "Generated",
                    "Weight": 0.99
                  }
                ],
                "Roles": {
                  "transaçõe": {
                    "Target": {
                      "Entity": "transaçõe"
                    }
                  },
                  "transaçõe.tipo": {
                    "Target": {
                      "Entity": "transaçõe.tipo"
                    }
                  }
                },
                "State": "Generated"
              },
              "transaçõe_has_tipo_subunidade": {
                "Binding": {
                  "ConceptualEntity": "Transações"
                },
                "Phrasings": [
                  {
                    "Attribute": {
                      "Object": {
                        "Role": "transaçõe.tipo_subunidade"
                      },
                      "Subject": {
                        "Role": "transaçõe"
                      }
                    },
                    "ID": "transações_have_tipo_subunidades",
                    "State": "Generated",
                    "Weight": 0.99
                  }
                ],
                "Roles": {
                  "transaçõe": {
                    "Target": {
                      "Entity": "transaçõe"
                    }
                  },
                  "transaçõe.tipo_subunidade": {
                    "Target": {
                      "Entity": "transaçõe.tipo_subunidade"
                    }
                  }
                },
                "State": "Generated"
              }
            },
            "Version": "4.1.0"
          },
          "contentType": "json"
        }
      }
    ],
    "dataAccessOptions": {
      "legacyRedirects": true,
      "returnErrorValuesAsNull": true
    },
    "defaultPowerBIDataSourceVersion": "powerBI_V3",
    "expressions": [
      {
        "name": "Errors in Transações",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "expression": [
          "let",
          "Source = Transações,",
          "  #\"Detected Type Mismatches\" = let",
          "    tableWithOnlyPrimitiveTypes = Table.SelectColumns(Source, Table.ColumnsOfType(Source, {type nullable number, type nullable text, type nullable logical, type nullable date, type nullable datetime, type nullable datetimezone, type nullable time, type nullable duration})),",
          "    recordTypeFields = Type.RecordFields(Type.TableRow(Value.Type(tableWithOnlyPrimitiveTypes))),",
          "    fieldNames = Record.FieldNames(recordTypeFields),",
          "    fieldTypes = List.Transform(Record.ToList(recordTypeFields), each [Type]),",
          "    pairs = List.Transform(List.Positions(fieldNames), (i) => {fieldNames{i}, (v) => if v = null or Value.Is(v, fieldTypes{i}) then v else error [Message = \"The type of the value does not match the type of the column.\", Detail = v], fieldTypes{i}})",
          "in",
          "    Table.TransformColumns(Source, pairs),",
          "  #\"Added Index\" = Table.AddIndexColumn(#\"Detected Type Mismatches\", \"Row Number\" ,1),",
          "  #\"Kept Errors\" = Table.SelectRowsWithErrors(#\"Added Index\", {\"Linha\", \"Data Lançamento\", \"Montante (signed)\", \"Subunidade\", \"Tipo subunidade\", \"Finalidade\", \"Finalidade (detalhada)\", \"Pago\", \"Tipo\", \"Descrição + Beneficiário\", \"Doc de Solitação\", \"Doc de Pagamento\", \"Lista SIAFI\", \"Empenho SIE\", \"Empenho SIAFI\", \"Local / Trecho\", \"Quantidade\"}),",
          "  #\"Reordered Columns\" = Table.ReorderColumns(#\"Kept Errors\", {\"Row Number\", \"Linha\", \"Data Lançamento\", \"Montante (signed)\", \"Subunidade\", \"Tipo subunidade\", \"Finalidade\", \"Finalidade (detalhada)\", \"Pago\", \"Tipo\", \"Descrição + Beneficiário\", \"Doc de Solitação\", \"Doc de Pagamento\", \"Lista SIAFI\", \"Empenho SIE\", \"Empenho SIAFI\", \"Local / Trecho\", \"Quantidade\"})",
          "in",
          "  #\"Reordered Columns\""
        ],
        "kind": "m",
        "lineageTag": "38e9d582-874b-4907-afbb-f21d29702652",
        "queryGroup": "Query Errors - 10/03/2026 08:05:28"
      }
    ],
    "queryGroups": [
      {
        "annotations": [
          {
            "name": "PBI_QueryGroupOrder",
            "value": "0"
          }
        ],
        "description": "Errors in queries that were loaded on 10/03/2026 08:05:28.",
        "folder": "Query Errors - 10/03/2026 08:05:28"
      }
    ],
    "relationships": [
      {
        "name": "e60f0846-7b52-9bbc-6d72-54d8ad8d05c3",
        "fromColumn": "Finalidade",
        "fromTable": "Transações",
        "toColumn": "Finalidade",
        "toTable": "dFinalidades"
      },
      {
        "name": "279993c4-edb6-e01a-a466-ccab8159ca87",
        "fromColumn": "Subunidade",
        "fromTable": "Transações",
        "toColumn": "Nome",
        "toTable": "dSubunidades"
      },
      {
        "name": "3ba87e23-4898-4399-8977-80c5641e341c",
        "fromColumn": "Date",
        "fromTable": "dCalendario",
        "joinOnDateBehavior": "datePartOnly",
        "toColumn": "Date",
        "toTable": "LocalDateTable_32e1f282-8cf9-463b-9322-a13d5ca45473"
      },
      {
        "name": "4d2e7ce1-0ee8-5515-7ef4-6c79cae03a5f",
        "fromColumn": "Data Lançamento",
        "fromTable": "Transações",
        "toColumn": "Date",
        "toTable": "dCalendario"
      },
      {
        "name": "d94439b9-4532-9da1-d7b1-3f411e7490d6",
        "fromColumn": "Linha",
        "fromTable": "Transações",
        "toColumn": "Linhas (em azul) com dados faltantes",
        "toTable": "pendências"
      }
    ],
    "sourceQueryCulture": "pt-BR",
    "tables": [
      {
        "name": "Transações",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "Linha",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "108fec05-e8a9-45fb-bd50-edcb41047ff9",
            "sourceColumn": "Linha",
            "summarizeBy": "none"
          },
          {
            "name": "Data Lançamento",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Short Date",
            "lineageTag": "e749102b-cafa-4291-a588-6ab766fb45a9",
            "sourceColumn": "Data Lançamento",
            "summarizeBy": "none"
          },
          {
            "name": "Montante",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"pt-BR\"}"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "double",
            "formatString": "\"R$\"\\ #,0.00;-\"R$\"\\ #,0.00;\"R$\"\\ #,0.00",
            "lineageTag": "ec99ea6d-faab-40a2-a9e2-3738a69537b1",
            "sourceColumn": "Montante",
            "summarizeBy": "sum"
          },
          {
            "name": "Subunidade",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "eb5a8eab-6f8d-4e47-840c-ca9316e84ee5",
            "sourceColumn": "Subunidade",
            "summarizeBy": "none"
          },
          {
            "name": "Finalidade",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "14567775-6804-4adb-a195-2baf86ac8940",
            "sourceColumn": "Finalidade",
            "summarizeBy": "none"
          },
          {
            "name": "Tipo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "430762df-2eac-422c-9771-6a7113145487",
            "sourceColumn": "Tipo",
            "summarizeBy": "none"
          },
          {
            "name": "Finalidade (detalhada)",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "f331fc9c-896b-4104-a22d-17b2dd524ee4",
            "sourceColumn": "Finalidade (detalhada)",
            "summarizeBy": "none"
          },
          {
            "name": "Tipo subunidade",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "67ecea68-60cd-40c9-86ee-7d90ed15de34",
            "sourceColumn": "Tipo subunidade",
            "summarizeBy": "none"
          },
          {
            "name": "Pago",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "boolean",
            "formatString": "\"TRUE\";\"TRUE\";\"FALSE\"",
            "lineageTag": "2d0c5d08-2d15-4c43-8ce5-83e2a41bab4b",
            "sourceColumn": "Pago",
            "summarizeBy": "none"
          },
          {
            "name": "Doc de Solitação",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "cc619a9f-ca9f-4fc9-a35a-623adfc355f0",
            "sourceColumn": "Doc de Solitação",
            "summarizeBy": "none"
          },
          {
            "name": "Doc de Pagamento",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "5e0db7aa-dbe8-4ddf-9fed-0d83cc0848b8",
            "sourceColumn": "Doc de Pagamento",
            "summarizeBy": "none"
          },
          {
            "name": "Lista SIAFI",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "28700cbc-4a9e-4dc7-b318-761934029d6c",
            "sourceColumn": "Lista SIAFI",
            "summarizeBy": "none"
          },
          {
            "name": "Empenho SIE",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "9f887121-315d-428a-a865-fba381d28034",
            "sourceColumn": "Empenho SIE",
            "summarizeBy": "none"
          },
          {
            "name": "Empenho SIAFI",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "8a789568-1796-4f9e-ad86-65a2a5a85c6e",
            "sourceColumn": "Empenho SIAFI",
            "summarizeBy": "none"
          },
          {
            "name": "Local / Trecho",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "3f7bc5ee-6ed4-4b54-bdbc-c1b08bb5b1da",
            "sourceColumn": "Local / Trecho",
            "summarizeBy": "none"
          },
          {
            "name": "Quantidade",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "7ce7d165-8b79-486c-94ce-a8e90d75b6e0",
            "sourceColumn": "Quantidade",
            "summarizeBy": "none"
          },
          {
            "name": "Descrição + Beneficiário",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "8dc882b5-8b49-4416-a789-29887ebcda29",
            "sourceColumn": "Descrição + Beneficiário",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "d4a51c54-a899-4bbd-9d9b-358e6d75fa7f",
        "measures": [
          {
            "name": "Débitos totais",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"pt-BR\"}"
              }
            ],
            "expression": [
              "CALCULATE(",
              "    SUM('Transações'[Montante]),",
              "    'Transações'[Tipo] = \"Débito\"",
              ")"
            ],
            "formatString": "\"R$\"\\ #,0.00;-\"R$\"\\ #,0.00;\"R$\"\\ #,0.00",
            "lineageTag": "1bbf3f09-a786-48cd-a867-ffe7073d7b57"
          },
          {
            "name": "Créditos totais",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"pt-BR\"}"
              }
            ],
            "expression": [
              "CALCULATE(",
              "    SUM('Transações'[Montante]),",
              "    'Transações'[Tipo] = \"Crédito\"",
              ")"
            ],
            "formatString": "\"R$\"\\ #,0.00;-\"R$\"\\ #,0.00;\"R$\"\\ #,0.00",
            "lineageTag": "9366692b-92ee-4e1b-9e7f-9eb20972b685"
          },
          {
            "name": "Créditos IDR",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"pt-BR\"}"
              }
            ],
            "expression": [
              "CALCULATE(",
              "    SUM('Transações'[Montante]),",
              "    'Transações'[Tipo] = \"Crédito\",",
              "    FILTER(",
              "        'Transações',",
              "        'Transações'[Finalidade] = \"IDR - Custeio\" || 'Transações'[Finalidade] = \"IDR - Capital\"",
              "    )",
              ")"
            ],
            "formatString": "\"R$\"\\ #,0.00;-\"R$\"\\ #,0.00;\"R$\"\\ #,0.00",
            "lineageTag": "63e86dae-bb4e-4cd2-8dd8-8de48d5d01a3"
          },
          {
            "name": "Créditos transferências",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": [
              "CALCULATE(",
              "    SUM('Transações'[Montante]),",
              "    'Transações'[Tipo] = \"Crédito\",",
              "    FILTER(",
              "        'Transações',",
              "        ('Transações'[Finalidade] = \"Transferência - Custeio\") || ('Transações'[Finalidade] = \"Transferência - Capital\")",
              "    )",
              ")"
            ],
            "lineageTag": "ca34cedf-04ae-4757-9391-c42bb7569342"
          },
          {
            "name": "Débitos transferências",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"pt-BR\"}"
              }
            ],
            "expression": [
              "CALCULATE(",
              "    SUM('Transações'[Montante]),",
              "    'Transações'[Tipo] = \"Débito\",",
              "    ('Transações'[Finalidade] = \"Transferência - Custeio\") || ('Transações'[Finalidade] = \"Transferência - Capital\")",
              ")"
            ],
            "formatString": "\"R$\"\\ #,0.00;-\"R$\"\\ #,0.00;\"R$\"\\ #,0.00",
            "lineageTag": "cb9f292d-9ea0-4b74-81ce-8b520f2d3843"
          },
          {
            "name": "Débitos totais a pagar",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": [
              "CALCULATE(",
              "    SUM('Transações'[Montante]),",
              "    'Transações'[Tipo] = \"Débito\",",
              "    'Transações'[Pago] = FALSE",
              ")"
            ],
            "lineageTag": "ac25965d-99fe-4798-935f-56b964296bf6"
          },
          {
            "name": "Débitos totais pagos",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": [
              "CALCULATE(",
              "    SUM('Transações'[Montante]),",
              "    'Transações'[Tipo] = \"Débito\",",
              "    'Transações'[Pago] = TRUE",
              ")"
            ],
            "lineageTag": "dbdeebfa-2935-4423-b61a-ca3f29f34d1e"
          }
        ],
        "partitions": [
          {
            "name": "Transações",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = GoogleSheets.Contents(\"https://docs.google.com/spreadsheets/d/1_Xtx0snoLOuKp9DWR1D9C6kG4rZpVVOQyo8zCd1N5fY/edit?usp=sharing\"),",
                "    NS2_Table = Source{[name=\"NS2\",ItemKind=\"Table\"]}[Data],",
                "    #\"Promoted Headers\" = Table.PromoteHeaders(NS2_Table, [PromoteAllScalars=true]),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Promoted Headers\",{{\"Linha\", Int64.Type}, {\"Data Lançamento\", type date}, {\"Montante (R$)\", type number}, {\"Subunidade\", type text}, {\"Finalidade\", type text}, {\"Tipo\", type text}}),",
                "    #\"Removed Blank Rows\" = Table.SelectRows(#\"Changed Type\", each not List.IsEmpty(List.RemoveMatchingItems(Record.FieldValues(_), {\"\", null}))),",
                "    #\"Changed Type1\" = Table.TransformColumnTypes(#\"Removed Blank Rows\",{{\"Data Lançamento\", type datetime}}),",
                "    #\"Renamed Columns\" = Table.RenameColumns(#\"Changed Type1\",{{\"Montante (R$)\", \"Montante (signed)\"}}),",
                "    #\"Replaced Value\" = Table.ReplaceValue(#\"Renamed Columns\",\"sim\",\"True\",Replacer.ReplaceText,{\"Pago\"}),",
                "    #\"Replaced Value1\" = Table.ReplaceValue(#\"Replaced Value\",\"não\",\"False\",Replacer.ReplaceText,{\"Pago\"}),",
                "    #\"Changed Type2\" = Table.TransformColumnTypes(#\"Replaced Value1\",{{\"Pago\", type logical}}),",
                "    #\"Merged Columns\" = Table.CombineColumns(#\"Changed Type2\",{\"Descrição\", \"Nome / Beneficiário / Setor\"},Combiner.CombineTextByDelimiter(\". \", QuoteStyle.None),\"Descrição + Beneficiário\"),",
                "    #\"Reordered Columns\" = Table.ReorderColumns(#\"Merged Columns\",{\"Linha\", \"Data Lançamento\", \"Montante (signed)\", \"Subunidade\", \"Tipo subunidade\", \"Finalidade\", \"Finalidade (detalhada)\", \"Pago\", \"Tipo\", \"Descrição + Beneficiário\", \"Doc de Solitação\", \"Doc de Pagamento\", \"Lista SIAFI\", \"Empenho SIE\", \"Empenho SIAFI\", \"Local / Trecho\", \"Quantidade\"}),",
                "    #\"Renamed Columns1\" = Table.RenameColumns(#\"Reordered Columns\",{{\"Montante (signed)\", \"Montante\"}}),",
                "    #\"Calculated Absolute Value\" = Table.TransformColumns(#\"Renamed Columns1\",{{\"Montante\", Number.Abs, type number}})",
                "in",
                "    #\"Calculated Absolute Value\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "dFinalidades",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "Finalidade",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "b7fca72e-6ce0-4438-a1d2-8f3dcb9b35b8",
            "sourceColumn": "Finalidade",
            "summarizeBy": "none"
          },
          {
            "name": "Tipo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "2c13ec9a-b26c-42d0-9d9e-56716e00b376",
            "sourceColumn": "Tipo",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "38544813-ed5c-4f44-a6b6-d0eedb8dbf8d",
        "partitions": [
          {
            "name": "dFinalidades",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = GoogleSheets.Contents(\"https://docs.google.com/spreadsheets/d/1_Xtx0snoLOuKp9DWR1D9C6kG4rZpVVOQyo8zCd1N5fY/edit?usp=sharing\"),",
                "    #\"lista - tipos de finalidades_Table\" = Source{[name=\"lista - tipos de finalidades\",ItemKind=\"Table\"]}[Data],",
                "    #\"Promoted Headers\" = Table.PromoteHeaders(#\"lista - tipos de finalidades_Table\", [PromoteAllScalars=true])",
                "in",
                "    #\"Promoted Headers\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "dSubunidades",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "Nome",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "092c91eb-ed01-47cc-849c-933c1ff35cc3",
            "sourceColumn": "Nome",
            "summarizeBy": "none"
          },
          {
            "name": "Classificação",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "04f8947a-1940-4941-b5a6-4b66a5300d5d",
            "sourceColumn": "Classificação",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "faa5b78d-1a10-47cd-b8c2-0aae1e4e3bab",
        "partitions": [
          {
            "name": "dSubunidades",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = GoogleSheets.Contents(\"https://docs.google.com/spreadsheets/d/1_Xtx0snoLOuKp9DWR1D9C6kG4rZpVVOQyo8zCd1N5fY/edit?usp=sharing\"),",
                "    #\"lista - subunidades_Table\" = Source{[name=\"lista - subunidades\",ItemKind=\"Table\"]}[Data],",
                "    #\"Promoted Headers\" = Table.PromoteHeaders(#\"lista - subunidades_Table\", [PromoteAllScalars=true]),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Promoted Headers\",{{\"Nome\", type text}, {\"Classificação\", type text}})",
                "in",
                "    #\"Changed Type\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "dCalendario",
        "annotations": [
          {
            "name": "PBI_Id",
            "value": "cc8c282432de47f4bdd228e0cb61ac03"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "dateTime",
            "formatString": "General Date",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "ad4d94e7-4caf-4efc-afa4-01b479e95a4b",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn",
            "variations": [
              {
                "name": "Variation",
                "defaultHierarchy": {
                  "hierarchy": "Date Hierarchy",
                  "table": "LocalDateTable_32e1f282-8cf9-463b-9322-a13d5ca45473"
                },
                "isDefault": true,
                "relationship": "3ba87e23-4898-4399-8977-80c5641e341c"
              }
            ]
          },
          {
            "name": "Ano",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "6e1d94c5-daee-4347-9658-3499ae5fd3f1",
            "sourceColumn": "[Ano]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Mês num",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "fb2816b4-36d9-4f2e-a9d3-2183bff3caac",
            "sourceColumn": "[Mês num]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Mês nome",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "9d4f3b30-591c-4dbe-a168-ccded5078b48",
            "sortByColumn": "Mês num",
            "sourceColumn": "[Mês nome]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Dia",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "ba29f0fb-309d-46ee-bad3-dd3e92f2745b",
            "sourceColumn": "[Dia]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Ano atual",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "c794b912-7821-4d02-9ff2-5b3d1e9dbdc3",
            "sourceColumn": "[Ano atual]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Mês atual",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "49988213-6192-4a32-9135-1e8bf6e29c0f",
            "sourceColumn": "[Mês atual]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Dia atual",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "db5bd9de-54ac-4d06-8584-228b03954481",
            "sourceColumn": "[Dia atual]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          }
        ],
        "lineageTag": "720f87c4-3e12-4102-a7ce-ee754875170c",
        "partitions": [
          {
            "name": "dCalendario",
            "mode": "import",
            "source": {
              "expression": [
                "ADDCOLUMNS (",
                "    CALENDARAUTO(),",
                "    \"Ano\", YEAR ( [Date] ),",
                "    \"Mês num\", MONTH ( [Date] ),",
                "    \"Mês nome\",  SWITCH(",
                "        MONTH ([Date]),",
                "        1,\"Janeiro\",",
                "        2,\"Fevereiro\",",
                "        3,\"Março\",",
                "        4,\"Abril\",",
                "        5,\"Maio\",",
                "        6,\"Junho\",",
                "        7,\"Julho\",",
                "        8,\"Agosto\",",
                "        9,\"Setembro\",",
                "        10,\"Outubro\",",
                "        11,\"Novembro\",",
                "        12,\"Dezembro\"",
                "    ),",
                "    \"Dia\", DAY ( [Date] ),",
                "    \"Ano atual\", IF ( YEAR ( [Date] ) = YEAR ( TODAY () ), \"S\", \"N\" ),",
                "    \"Mês atual\",",
                "        IF (",
                "            YEAR ( [Date] ) = YEAR ( TODAY () )",
                "                && MONTH ( [Date] ) = MONTH ( TODAY () ),",
                "            \"S\",",
                "            \"N\"",
                "        ),",
                "    \"Dia atual\",",
                "        IF (",
                "            YEAR ( [Date] ) = YEAR ( TODAY () )",
                "                && MONTH ( [Date] ) = MONTH ( TODAY () )",
                "                && DAY ( [Date] ) = DAY ( TODAY () ),",
                "            \"S\",",
                "            \"N\"",
                "        )",
                ")"
              ],
              "type": "calculated"
            }
          }
        ]
      },
      {
        "name": "DateTableTemplate_d8ff267f-2e67-4d2c-9fc2-906d6fc4043c",
        "annotations": [
          {
            "name": "__PBI_TemplateDateTable",
            "value": "true"
          },
          {
            "name": "DefaultItem",
            "value": "DateHierarchy"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "formatString": "General Date",
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "d965f7e0-4330-429b-b0a9-5912620f9c02",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "ec1385d5-8345-4135-8177-bc32e0806ea8",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "25c0c5cc-b90c-4b31-b620-984ef5a4124f",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isHidden": true,
            "lineageTag": "dc8143f6-6b6b-42cb-9639-eb8145ab33b7",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "ea656df0-94f6-4537-b9b4-1de23341a9c6",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Quarter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Qtr \" & [QuarterNo]",
            "isHidden": true,
            "lineageTag": "f0585822-5dd6-459d-bc17-f29c619c9c05",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Day",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "75316963-8dcf-4910-9ac2-037877d4f79a",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Date Hierarchy",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Year",
                "column": "Year",
                "lineageTag": "ac07dbd8-41d7-48e6-b2e2-2a04f1d8179d",
                "ordinal": 0
              },
              {
                "name": "Quarter",
                "column": "Quarter",
                "lineageTag": "3f1fabae-efa4-48c6-bc68-d5709c9b7b9e",
                "ordinal": 1
              },
              {
                "name": "Month",
                "column": "Month",
                "lineageTag": "ab72b66b-8fcc-4a2e-aff2-b459e3937883",
                "ordinal": 2
              },
              {
                "name": "Day",
                "column": "Day",
                "lineageTag": "f99b19bf-6b44-44aa-951c-55c79dbf9424",
                "ordinal": 3
              }
            ],
            "lineageTag": "a7edd956-2f35-4909-8147-1bf8c03a4ece"
          }
        ],
        "isHidden": true,
        "isPrivate": true,
        "lineageTag": "b5766227-6d7b-44eb-b991-2414398c99ba",
        "partitions": [
          {
            "name": "DateTableTemplate_d8ff267f-2e67-4d2c-9fc2-906d6fc4043c",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(2015,1,1), Date(2015,1,1))",
              "type": "calculated"
            }
          }
        ]
      },
      {
        "name": "LocalDateTable_32e1f282-8cf9-463b-9322-a13d5ca45473",
        "annotations": [
          {
            "name": "__PBI_LocalDateTable",
            "value": "true"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "formatString": "General Date",
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "c7675b14-0923-4fe9-961d-bdee0784ce95",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "b1b02560-e7e0-4555-ae8c-0e2f8d849900",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "e5b60961-c830-4d45-bb4d-b9c003ecf6f5",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isHidden": true,
            "lineageTag": "ff82cc38-4e74-4d88-bcf4-16a1f7fa56ae",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "81724443-4f7b-473d-b76a-e3b237ecd20f",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Quarter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Qtr \" & [QuarterNo]",
            "isHidden": true,
            "lineageTag": "f8921654-9cd1-4cb2-88ab-32d81b3a4fac",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Day",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "a5026ca7-aa23-40a8-ba18-53bc8aeda231",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Date Hierarchy",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Year",
                "column": "Year",
                "lineageTag": "95538929-4d55-438b-ad2e-95ae50ccb1f9",
                "ordinal": 0
              },
              {
                "name": "Quarter",
                "column": "Quarter",
                "lineageTag": "32b21537-4bd0-4940-bb55-1620fef23902",
                "ordinal": 1
              },
              {
                "name": "Month",
                "column": "Month",
                "lineageTag": "5c2748ba-6421-40ae-974c-e0e737a992dc",
                "ordinal": 2
              },
              {
                "name": "Day",
                "column": "Day",
                "lineageTag": "3102459c-b836-442e-8648-1fc0ee40c162",
                "ordinal": 3
              }
            ],
            "lineageTag": "3cc9c8e7-77d1-43fe-abb3-69c89b5fd959"
          }
        ],
        "isHidden": true,
        "lineageTag": "0ea247a3-7ca2-4337-8d33-ab41ff750d97",
        "partitions": [
          {
            "name": "LocalDateTable_32e1f282-8cf9-463b-9322-a13d5ca45473",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(Year(MIN('dCalendario'[Date])), 1, 1), Date(Year(MAX('dCalendario'[Date])), 12, 31))",
              "type": "calculated"
            }
          }
        ],
        "showAsVariationsOnly": true
      },
      {
        "name": "pendências",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "Linhas (em azul) com dados faltantes",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "54ee876f-a688-4085-a8da-f49a26fa2716",
            "sourceColumn": "Linhas (em azul) com dados faltantes",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "9f45732d-740e-42db-a28e-da89144e3e7d",
        "partitions": [
          {
            "name": "pendências",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = GoogleSheets.Contents(\"https://docs.google.com/spreadsheets/d/1_Xtx0snoLOuKp9DWR1D9C6kG4rZpVVOQyo8zCd1N5fY/edit?usp=sharing\"),",
                "    pendências_Table = Source{[name=\"pendências\",ItemKind=\"Table\"]}[Data],",
                "    #\"Promoted Headers\" = Table.PromoteHeaders(pendências_Table, [PromoteAllScalars=true]),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Promoted Headers\",{{\"Linhas (em azul) com dados faltantes\", type text}})",
                "in",
                "    #\"Changed Type\""
              ],
              "type": "m"
            }
          }
        ]
      }
    ]
  }
}