{
  "compatibilityLevel": 1601,
  "model": {
    "annotations": [
      {
        "name": "__PBI_TimeIntelligenceEnabled",
        "value": "1"
      },
      {
        "name": "PBI_QueryOrder",
        "value": "[\"Transações\",\"dFinalidades\",\"dSubunidades\",\"Errors in Transações\"]"
      },
      {
        "name": "PBI_ProTooling",
        "value": "[\"DevMode\"]"
      }
    ],
    "culture": "en-US",
    "cultures": [
      {
        "name": "en-US",
        "linguisticMetadata": {}
      }
    ],
    "dataAccessOptions": {
      "legacyRedirects": true,
      "returnErrorValuesAsNull": true
    },
    "defaultPowerBIDataSourceVersion": "powerBI_V3",
    "expressions": [
      {
        "name": "Errors in Transações",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "expression": [
          "let",
          "Source = Transações,",
          "  #\"Detected Type Mismatches\" = let",
          "    tableWithOnlyPrimitiveTypes = Table.SelectColumns(Source, Table.ColumnsOfType(Source, {type nullable number, type nullable text, type nullable logical, type nullable date, type nullable datetime, type nullable datetimezone, type nullable time, type nullable duration})),",
          "    recordTypeFields = Type.RecordFields(Type.TableRow(Value.Type(tableWithOnlyPrimitiveTypes))),",
          "    fieldNames = Record.FieldNames(recordTypeFields),",
          "    fieldTypes = List.Transform(Record.ToList(recordTypeFields), each [Type]),",
          "    pairs = List.Transform(List.Positions(fieldNames), (i) => {fieldNames{i}, (v) => if v = null or Value.Is(v, fieldTypes{i}) then v else error [Message = \"The type of the value does not match the type of the column.\", Detail = v], fieldTypes{i}})",
          "in",
          "    Table.TransformColumns(Source, pairs),",
          "  #\"Added Index\" = Table.AddIndexColumn(#\"Detected Type Mismatches\", \"Row Number\" ,1),",
          "  #\"Kept Errors\" = Table.SelectRowsWithErrors(#\"Added Index\", {\"Linha\", \"Data Lançamento\", \"Montante (signed)\", \"Subunidade\", \"Tipo subunidade\", \"Finalidade\", \"Finalidade (detalhada)\", \"Pago\", \"Tipo\", \"Descrição + Beneficiário\", \"Doc de Solitação\", \"Doc de Pagamento\", \"Lista SIAFI\", \"Empenho SIE\", \"Empenho SIAFI\", \"Local / Trecho\", \"Quantidade\"}),",
          "  #\"Reordered Columns\" = Table.ReorderColumns(#\"Kept Errors\", {\"Row Number\", \"Linha\", \"Data Lançamento\", \"Montante (signed)\", \"Subunidade\", \"Tipo subunidade\", \"Finalidade\", \"Finalidade (detalhada)\", \"Pago\", \"Tipo\", \"Descrição + Beneficiário\", \"Doc de Solitação\", \"Doc de Pagamento\", \"Lista SIAFI\", \"Empenho SIE\", \"Empenho SIAFI\", \"Local / Trecho\", \"Quantidade\"})",
          "in",
          "  #\"Reordered Columns\""
        ],
        "kind": "m",
        "lineageTag": "38e9d582-874b-4907-afbb-f21d29702652",
        "queryGroup": "Query Errors - 10/03/2026 08:05:28"
      }
    ],
    "queryGroups": [
      {
        "annotations": [
          {
            "name": "PBI_QueryGroupOrder",
            "value": "0"
          }
        ],
        "description": "Errors in queries that were loaded on 10/03/2026 08:05:28.",
        "folder": "Query Errors - 10/03/2026 08:05:28"
      }
    ],
    "relationships": [
      {
        "name": "e60f0846-7b52-9bbc-6d72-54d8ad8d05c3",
        "fromColumn": "Finalidade",
        "fromTable": "Transações",
        "toColumn": "Finalidade",
        "toTable": "dFinalidades"
      },
      {
        "name": "3ba87e23-4898-4399-8977-80c5641e341c",
        "fromColumn": "Date",
        "fromTable": "dCalendario",
        "joinOnDateBehavior": "datePartOnly",
        "toColumn": "Date",
        "toTable": "LocalDateTable_32e1f282-8cf9-463b-9322-a13d5ca45473"
      },
      {
        "name": "4d2e7ce1-0ee8-5515-7ef4-6c79cae03a5f",
        "fromColumn": "Data Lançamento",
        "fromTable": "Transações",
        "toColumn": "Date",
        "toTable": "dCalendario"
      },
      {
        "name": "AutoDetected_db8a1892-c11f-4017-98f9-fa7bc80c03e8",
        "fromColumn": "Subunidade",
        "fromTable": "Transações",
        "toColumn": "Subunidade",
        "toTable": "dSubunidades"
      }
    ],
    "sourceQueryCulture": "pt-BR",
    "tables": [
      {
        "name": "Transações",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "Linha",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "108fec05-e8a9-45fb-bd50-edcb41047ff9",
            "sourceColumn": "Linha",
            "summarizeBy": "none"
          },
          {
            "name": "Data Lançamento",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Short Date",
            "lineageTag": "e749102b-cafa-4291-a588-6ab766fb45a9",
            "sourceColumn": "Data Lançamento",
            "summarizeBy": "none"
          },
          {
            "name": "Montante",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"pt-BR\"}"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "double",
            "formatString": "\"R$\"\\ #,0.00;-\"R$\"\\ #,0.00;\"R$\"\\ #,0.00",
            "lineageTag": "ec99ea6d-faab-40a2-a9e2-3738a69537b1",
            "sourceColumn": "Montante",
            "summarizeBy": "sum"
          },
          {
            "name": "Subunidade",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "eb5a8eab-6f8d-4e47-840c-ca9316e84ee5",
            "sourceColumn": "Subunidade",
            "summarizeBy": "none"
          },
          {
            "name": "Finalidade",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "14567775-6804-4adb-a195-2baf86ac8940",
            "sourceColumn": "Finalidade",
            "summarizeBy": "none"
          },
          {
            "name": "Pago",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "boolean",
            "formatString": "\"TRUE\";\"TRUE\";\"FALSE\"",
            "isHidden": true,
            "lineageTag": "2d0c5d08-2d15-4c43-8ce5-83e2a41bab4b",
            "sourceColumn": "Pago",
            "summarizeBy": "none"
          },
          {
            "name": "Doc de Solitação",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "cc619a9f-ca9f-4fc9-a35a-623adfc355f0",
            "sourceColumn": "Doc de Solitação",
            "summarizeBy": "none"
          },
          {
            "name": "Doc de Pagamento",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "5e0db7aa-dbe8-4ddf-9fed-0d83cc0848b8",
            "sourceColumn": "Doc de Pagamento",
            "summarizeBy": "none"
          },
          {
            "name": "Lista SIAFI",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "28700cbc-4a9e-4dc7-b318-761934029d6c",
            "sourceColumn": "Lista SIAFI",
            "summarizeBy": "none"
          },
          {
            "name": "Empenho SIE",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "9f887121-315d-428a-a865-fba381d28034",
            "sourceColumn": "Empenho SIE",
            "summarizeBy": "none"
          },
          {
            "name": "Empenho SIAFI",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "8a789568-1796-4f9e-ad86-65a2a5a85c6e",
            "sourceColumn": "Empenho SIAFI",
            "summarizeBy": "none"
          },
          {
            "name": "Local / Trecho",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "3f7bc5ee-6ed4-4b54-bdbc-c1b08bb5b1da",
            "sourceColumn": "Local / Trecho",
            "summarizeBy": "none"
          },
          {
            "name": "Quantidade",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "7ce7d165-8b79-486c-94ce-a8e90d75b6e0",
            "sourceColumn": "Quantidade",
            "summarizeBy": "none"
          },
          {
            "name": "Descrição + Beneficiário",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "8dc882b5-8b49-4416-a789-29887ebcda29",
            "sourceColumn": "Descrição + Beneficiário",
            "summarizeBy": "none"
          },
          {
            "name": "Fluxo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "0dde17fc-8859-4ab2-ad8f-5278099ec0c7",
            "sourceColumn": "Fluxo",
            "summarizeBy": "none"
          },
          {
            "name": "Montante (signed)",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"pt-BR\"}"
              }
            ],
            "dataType": "double",
            "formatString": "\"R$\"\\ #,0.00;-\"R$\"\\ #,0.00;\"R$\"\\ #,0.00",
            "lineageTag": "4bd00013-8489-42b4-961d-cf75a1a42f5b",
            "sourceColumn": "Montante (signed)",
            "summarizeBy": "sum"
          }
        ],
        "lineageTag": "d4a51c54-a899-4bbd-9d9b-358e6d75fa7f",
        "measures": [
          {
            "name": "Débito Total",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"pt-BR\"}"
              }
            ],
            "expression": [
              "CALCULATE(",
              "    SUM('Transações'[Montante]),",
              "    'Transações'[Fluxo] = \"Débito\"",
              ")"
            ],
            "formatString": "\"R$\"\\ #,0.00;-\"R$\"\\ #,0.00;\"R$\"\\ #,0.00",
            "lineageTag": "1bbf3f09-a786-48cd-a867-ffe7073d7b57"
          },
          {
            "name": "Crédito Total",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"pt-BR\"}"
              }
            ],
            "expression": [
              "CALCULATE(",
              "    SUM('Transações'[Montante]),",
              "    'Transações'[Fluxo] = \"Crédito\"",
              ")"
            ],
            "formatString": "\"R$\"\\ #,0.00;-\"R$\"\\ #,0.00;\"R$\"\\ #,0.00",
            "lineageTag": "9366692b-92ee-4e1b-9e7f-9eb20972b685"
          },
          {
            "name": "Crédito IDR Total",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"pt-BR\"}"
              }
            ],
            "expression": [
              "CALCULATE(",
              "    SUM('Transações'[Montante]),",
              "    'Transações'[Fluxo] = \"Crédito\",",
              "    dFinalidades[Modalidade] = \"IDR\"",
              ")"
            ],
            "formatString": "\"R$\"\\ #,0.00;-\"R$\"\\ #,0.00;\"R$\"\\ #,0.00",
            "lineageTag": "63e86dae-bb4e-4cd2-8dd8-8de48d5d01a3"
          },
          {
            "name": "Crédito Transferências Total",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"pt-BR\"}"
              }
            ],
            "expression": [
              "CALCULATE(",
              "    SUM('Transações'[Montante]),",
              "    'Transações'[Fluxo] = \"Crédito\",",
              "    dFinalidades[Modalidade] = \"Transferência\"",
              ")"
            ],
            "formatString": "\"R$\"\\ #,0.00;-\"R$\"\\ #,0.00;\"R$\"\\ #,0.00",
            "lineageTag": "ca34cedf-04ae-4757-9391-c42bb7569342"
          },
          {
            "name": "Débito Despesas Custeio",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"pt-BR\"}"
              }
            ],
            "expression": [
              "",
              "CALCULATE(",
              "    SUM('Transações'[Montante]),",
              "    'Transações'[Fluxo] = \"Débito\",",
              "    'dFinalidades'[Modalidade] = \"Despesas\",",
              "    'dFinalidades'[Natureza] = \"Custeio\"",
              ")"
            ],
            "formatString": "\"R$\"\\ #,0.00;-\"R$\"\\ #,0.00;\"R$\"\\ #,0.00",
            "lineageTag": "cb9f292d-9ea0-4b74-81ce-8b520f2d3843"
          },
          {
            "name": "Débito Despesas Total",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"pt-BR\"}"
              }
            ],
            "expression": [
              "",
              "CALCULATE(",
              "    SUM('Transações'[Montante]),",
              "    'Transações'[Fluxo] = \"Débito\",",
              "    'dFinalidades'[Modalidade] = \"Despesas\"",
              ")"
            ],
            "formatString": "\"R$\"\\ #,0.00;-\"R$\"\\ #,0.00;\"R$\"\\ #,0.00",
            "lineageTag": "cf019427-aef0-42e9-99df-5bef567841e0"
          },
          {
            "name": "Crédito IDR Custeio",
            "expression": [
              "CALCULATE(",
              "    SUM('Transações'[Montante]),",
              "    'Transações'[Fluxo] = \"Crédito\",",
              "    'dFinalidades'[Natureza] = \"Custeio\"",
              ")"
            ],
            "formatString": "\\$#,0.###############;(\\$#,0.###############);\\$#,0.###############",
            "lineageTag": "669762f8-5448-4ffe-ae0b-f192aed56da6"
          },
          {
            "name": "Crédito IDR Capital",
            "expression": [
              "CALCULATE(",
              "    SUM('Transações'[Montante]),",
              "    'Transações'[Fluxo] = \"Crédito\",",
              "    'dFinalidades'[Natureza] = \"Capital\"",
              ")"
            ],
            "formatString": "\\$#,0.###############;(\\$#,0.###############);\\$#,0.###############",
            "lineageTag": "799dd489-0387-4a5d-acf3-de3fe5bd3891"
          },
          {
            "name": "Crédito Transferências Custeio",
            "expression": [
              "CALCULATE(",
              "    SUM('Transações'[Montante]),",
              "    'Transações'[Fluxo] = \"Crédito\",",
              "    dFinalidades[Modalidade] = \"Transferência\",",
              "    dFinalidades[Natureza] = \"Custeio\"",
              ")"
            ],
            "formatString": "\\$#,0.###############;(\\$#,0.###############);\\$#,0.###############",
            "lineageTag": "825bd2d1-9909-47db-8f1e-dc4c022df8e6"
          },
          {
            "name": "Crédito Transferências Capital",
            "expression": [
              "CALCULATE(",
              "    SUM('Transações'[Montante]),",
              "    'Transações'[Fluxo] = \"Crédito\",",
              "    dFinalidades[Modalidade] = \"Transferência\",",
              "    dFinalidades[Natureza] = \"Capital\"",
              ")"
            ],
            "formatString": "\\$#,0.###############;(\\$#,0.###############);\\$#,0.###############",
            "lineageTag": "e2a12f02-8025-4b0f-963f-7daa7b903545"
          },
          {
            "name": "Débito Despesas Capital",
            "expression": [
              "",
              "CALCULATE(",
              "    SUM('Transações'[Montante]),",
              "    'Transações'[Fluxo] = \"Débito\",",
              "    'dFinalidades'[Modalidade] = \"Despesas\",",
              "    'dFinalidades'[Natureza] = \"Capital\"",
              ")"
            ],
            "formatString": "\\$#,0.###############;(\\$#,0.###############);\\$#,0.###############",
            "lineageTag": "5557e151-bb71-49f3-be80-5cf33764509a"
          },
          {
            "name": "Débito Transferências Total",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"pt-BR\"}"
              }
            ],
            "expression": [
              "CALCULATE(",
              "    SUM('Transações'[Montante]),",
              "    'Transações'[Fluxo] = \"Débito\",",
              "    'dFinalidades'[Modalidade] = \"Transferência\"",
              ")"
            ],
            "formatString": "\"R$\"\\ #,0.00;-\"R$\"\\ #,0.00;\"R$\"\\ #,0.00",
            "lineageTag": "c94ac4c6-9f6a-48f0-84f8-16718b402f48"
          },
          {
            "name": "Débito Transferências Custeio",
            "expression": [
              "CALCULATE(",
              "    SUM('Transações'[Montante]),",
              "    'Transações'[Fluxo] = \"Débito\",",
              "    'dFinalidades'[Modalidade] = \"Transferência\",",
              "    dFinalidades[Natureza] = \"Custeio\"",
              ")"
            ],
            "formatString": "\\$#,0.###############;(\\$#,0.###############);\\$#,0.###############",
            "lineageTag": "503c7a9e-f813-4cf1-ae4c-b75a0dbda45f"
          },
          {
            "name": "Débito Transferências Capital",
            "expression": [
              "CALCULATE(",
              "    SUM('Transações'[Montante]),",
              "    'Transações'[Fluxo] = \"Débito\",",
              "    'dFinalidades'[Modalidade] = \"Transferência\",",
              "    dFinalidades[Natureza] = \"Capital\"",
              ")"
            ],
            "formatString": "\\$#,0.###############;(\\$#,0.###############);\\$#,0.###############",
            "lineageTag": "d56d2eaf-154a-46b7-b917-151591fed5a1"
          },
          {
            "name": "Transferências Total",
            "expression": [
              "CALCULATE(",
              "    SUM('Transações'[Montante]),",
              "    'dFinalidades'[Modalidade] = \"Transferência\"",
              ")"
            ],
            "formatString": "\\$#,0.###############;(\\$#,0.###############);\\$#,0.###############",
            "lineageTag": "cd985786-c3c0-4cc4-bd5b-d04e6aaaa2e9"
          },
          {
            "name": "Despesas Total",
            "expression": [
              "CALCULATE(",
              "    SUM('Transações'[Montante]),",
              "    'dFinalidades'[Modalidade] = \"Despesas\"",
              ")"
            ],
            "formatString": "\\$#,0.###############;(\\$#,0.###############);\\$#,0.###############",
            "lineageTag": "caf001cb-15e6-4f41-8dba-4d6b0f5972d4"
          },
          {
            "name": "IDR Total",
            "expression": [
              "CALCULATE(",
              "    SUM('Transações'[Montante]),",
              "    'dFinalidades'[Modalidade] = \"IDR\"",
              ")"
            ],
            "formatString": "\\$#,0.###############;(\\$#,0.###############);\\$#,0.###############",
            "lineageTag": "cb8fdb50-d85e-43ab-a67f-f3a420318a5d"
          },
          {
            "name": "Custeio Total",
            "expression": [
              "CALCULATE(",
              "    SUM('Transações'[Montante]),",
              "    'dFinalidades'[Natureza] = \"Custeio\"",
              ")"
            ],
            "formatString": "\\$#,0.###############;(\\$#,0.###############);\\$#,0.###############",
            "lineageTag": "0b1d04df-671b-454d-8e07-e9ab4edeee98"
          },
          {
            "name": "Capital Total",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"pt-BR\"}"
              }
            ],
            "expression": [
              "CALCULATE(",
              "    SUM('Transações'[Montante]),",
              "    'dFinalidades'[Natureza] = \"Capital\"",
              ")"
            ],
            "formatString": "\"R$\"\\ #,0.00;-\"R$\"\\ #,0.00;\"R$\"\\ #,0.00",
            "lineageTag": "bd633c5c-2621-40cd-866c-c2fe878a46c6"
          },
          {
            "name": "Saldo",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"pt-BR\"}"
              }
            ],
            "expression": "[Crédito Total] - [Débito Total]",
            "formatString": "\"R$\"\\ #,0.00;-\"R$\"\\ #,0.00;\"R$\"\\ #,0.00",
            "lineageTag": "6fcdcbc0-213a-496e-b1aa-2ea66ea1e4fb"
          }
        ],
        "partitions": [
          {
            "name": "Transações",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = GoogleSheets.Contents(\"https://docs.google.com/spreadsheets/d/1_Xtx0snoLOuKp9DWR1D9C6kG4rZpVVOQyo8zCd1N5fY/edit?usp=sharing\"),",
                "    NS2_Table = Source{[name=\"NS2\",ItemKind=\"Table\"]}[Data],",
                "    #\"Promoted Headers\" = Table.PromoteHeaders(NS2_Table, [PromoteAllScalars=true]),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Promoted Headers\",{{\"Linha\", Int64.Type}, {\"Data Lançamento\", type date}, {\"Montante (R$)\", type number}, {\"Subunidade\", type text}, {\"Finalidade\", type text}, {\"Fluxo\", type text}}),",
                "    #\"Removed Blank Rows\" = Table.SelectRows(#\"Changed Type\", each not List.IsEmpty(List.RemoveMatchingItems(Record.FieldValues(_), {\"\", null}))),",
                "    #\"Changed Type1\" = Table.TransformColumnTypes(#\"Removed Blank Rows\",{{\"Data Lançamento\", type datetime}}),",
                "    #\"Renamed Columns\" = Table.RenameColumns(#\"Changed Type1\",{{\"Montante (R$)\", \"Montante (signed)\"}}),",
                "    #\"Replaced Value\" = Table.ReplaceValue(#\"Renamed Columns\",\"sim\",\"True\",Replacer.ReplaceText,{\"Pago\"}),",
                "    #\"Replaced Value1\" = Table.ReplaceValue(#\"Replaced Value\",\"não\",\"False\",Replacer.ReplaceText,{\"Pago\"}),",
                "    #\"Changed Type2\" = Table.TransformColumnTypes(#\"Replaced Value1\",{{\"Pago\", type logical}}),",
                "    #\"Merged Columns\" = Table.CombineColumns(#\"Changed Type2\",{\"Descrição\", \"Nome / Beneficiário / Setor\"},Combiner.CombineTextByDelimiter(\". \", QuoteStyle.None),\"Descrição + Beneficiário\"),",
                "    #\"Reordered Columns\" = Table.ReorderColumns(#\"Merged Columns\",{\"Linha\", \"Data Lançamento\", \"Montante (signed)\", \"Subunidade\", \"Tipo subunidade\", \"Finalidade (Grupo)\", \"Finalidade\", \"Pago\", \"Fluxo\", \"Descrição + Beneficiário\", \"Doc de Solitação\", \"Doc de Pagamento\", \"Lista SIAFI\", \"Empenho SIE\", \"Empenho SIAFI\", \"Local / Trecho\", \"Quantidade\"}),",
                "    #\"Renamed Columns1\" = Table.RenameColumns(#\"Reordered Columns\",{{\"Montante (signed)\", \"Montante\"}}),",
                "    #\"Duplicated Column\" = Table.DuplicateColumn(#\"Renamed Columns1\", \"Montante\", \"Montante - Copy\"),",
                "    #\"Renamed Columns2\" = Table.RenameColumns(#\"Duplicated Column\",{{\"Montante - Copy\", \"Montante (signed)\"}}),",
                "    #\"Reordered Columns1\" = Table.ReorderColumns(#\"Renamed Columns2\",{\"Linha\", \"Data Lançamento\", \"Montante\", \"Montante (signed)\", ",
                "\"Subunidade\", \"Tipo subunidade\", \"Finalidade (Grupo)\", \"Finalidade\", \"Pago\", \"Fluxo\", \"Descrição + Beneficiário\", \"Doc de Solitação\", \"Doc de Pagamento\", \"Lista SIAFI\", \"Empenho SIE\", \"Empenho SIAFI\", \"Local / Trecho\", \"Quantidade\"}),",
                "    #\"Calculated Absolute Value\" = Table.TransformColumns(#\"Reordered Columns1\",{{\"Montante\", Number.Abs, type number}}),",
                "    #\"Removed Columns\" = Table.RemoveColumns(#\"Calculated Absolute Value\",{\"Finalidade (Grupo)\", \"Tipo subunidade\"})",
                "in",
                "    #\"Removed Columns\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "dFinalidades",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "Finalidade",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "b7fca72e-6ce0-4438-a1d2-8f3dcb9b35b8",
            "sourceColumn": "Finalidade",
            "summarizeBy": "none"
          },
          {
            "name": "Modalidade",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "42a17c2e-8d62-464e-897d-f09fec477c95",
            "sourceColumn": "Modalidade",
            "summarizeBy": "none"
          },
          {
            "name": "Natureza",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "b7b6d759-27dc-41a7-a195-254f99023ca1",
            "sourceColumn": "Natureza",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "38544813-ed5c-4f44-a6b6-d0eedb8dbf8d",
        "partitions": [
          {
            "name": "dFinalidades",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = GoogleSheets.Contents(\"https://docs.google.com/spreadsheets/d/1_Xtx0snoLOuKp9DWR1D9C6kG4rZpVVOQyo8zCd1N5fY/edit?usp=sharing\"),",
                "    #\"lista - tipos de finalidades_Table\" = Source{[name=\"lista - tipos de finalidades\",ItemKind=\"Table\"]}[Data],",
                "    #\"Promoted Headers\" = Table.PromoteHeaders(#\"lista - tipos de finalidades_Table\", [PromoteAllScalars=true]),",
                "    #\"Removed Columns\" = Table.RemoveColumns(#\"Promoted Headers\",{\"Finalidade (Grupo)\"})",
                "in",
                "    #\"Removed Columns\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "dSubunidades",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "Subunidade",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "1114fb70-babe-4e3c-aee3-054ddbf41206",
            "sourceColumn": "Subunidade",
            "summarizeBy": "none"
          },
          {
            "name": "Grupo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "bcc2ccdb-949c-4e4e-880a-50741a4961f2",
            "sourceColumn": "Grupo",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "faa5b78d-1a10-47cd-b8c2-0aae1e4e3bab",
        "partitions": [
          {
            "name": "dSubunidades",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = GoogleSheets.Contents(\"https://docs.google.com/spreadsheets/d/1_Xtx0snoLOuKp9DWR1D9C6kG4rZpVVOQyo8zCd1N5fY/edit?usp=sharing\"),",
                "    #\"lista - subunidades_Table\" = Source{[name=\"lista - subunidades\",ItemKind=\"Table\"]}[Data],",
                "    #\"Promoted Headers\" = Table.PromoteHeaders(#\"lista - subunidades_Table\", [PromoteAllScalars=true]),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Promoted Headers\",{{\"Subunidade\", type text}, {\"Grupo\", type text}})",
                "in",
                "    #\"Changed Type\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "dCalendario",
        "annotations": [
          {
            "name": "PBI_Id",
            "value": "cc8c282432de47f4bdd228e0cb61ac03"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "dateTime",
            "formatString": "General Date",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "ad4d94e7-4caf-4efc-afa4-01b479e95a4b",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn",
            "variations": [
              {
                "name": "Variation",
                "defaultHierarchy": {
                  "hierarchy": "Date Hierarchy",
                  "table": "LocalDateTable_32e1f282-8cf9-463b-9322-a13d5ca45473"
                },
                "isDefault": true,
                "relationship": "3ba87e23-4898-4399-8977-80c5641e341c"
              }
            ]
          },
          {
            "name": "Ano",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "6e1d94c5-daee-4347-9658-3499ae5fd3f1",
            "sourceColumn": "[Ano]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Mês num",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "fb2816b4-36d9-4f2e-a9d3-2183bff3caac",
            "sourceColumn": "[Mês num]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Mês nome",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "9d4f3b30-591c-4dbe-a168-ccded5078b48",
            "sortByColumn": "Mês num",
            "sourceColumn": "[Mês nome]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Dia",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "ba29f0fb-309d-46ee-bad3-dd3e92f2745b",
            "sourceColumn": "[Dia]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Ano atual",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "c794b912-7821-4d02-9ff2-5b3d1e9dbdc3",
            "sourceColumn": "[Ano atual]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Mês atual",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "49988213-6192-4a32-9135-1e8bf6e29c0f",
            "sourceColumn": "[Mês atual]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Dia atual",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "db5bd9de-54ac-4d06-8584-228b03954481",
            "sourceColumn": "[Dia atual]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          }
        ],
        "lineageTag": "720f87c4-3e12-4102-a7ce-ee754875170c",
        "partitions": [
          {
            "name": "dCalendario",
            "mode": "import",
            "source": {
              "expression": [
                "ADDCOLUMNS (",
                "    CALENDARAUTO(),",
                "    \"Ano\", YEAR ( [Date] ),",
                "    \"Mês num\", MONTH ( [Date] ),",
                "    \"Mês nome\",  SWITCH(",
                "        MONTH ([Date]),",
                "        1,\"Janeiro\",",
                "        2,\"Fevereiro\",",
                "        3,\"Março\",",
                "        4,\"Abril\",",
                "        5,\"Maio\",",
                "        6,\"Junho\",",
                "        7,\"Julho\",",
                "        8,\"Agosto\",",
                "        9,\"Setembro\",",
                "        10,\"Outubro\",",
                "        11,\"Novembro\",",
                "        12,\"Dezembro\"",
                "    ),",
                "    \"Dia\", DAY ( [Date] ),",
                "    \"Ano atual\", IF ( YEAR ( [Date] ) = YEAR ( TODAY () ), \"S\", \"N\" ),",
                "    \"Mês atual\",",
                "        IF (",
                "            YEAR ( [Date] ) = YEAR ( TODAY () )",
                "                && MONTH ( [Date] ) = MONTH ( TODAY () ),",
                "            \"S\",",
                "            \"N\"",
                "        ),",
                "    \"Dia atual\",",
                "        IF (",
                "            YEAR ( [Date] ) = YEAR ( TODAY () )",
                "                && MONTH ( [Date] ) = MONTH ( TODAY () )",
                "                && DAY ( [Date] ) = DAY ( TODAY () ),",
                "            \"S\",",
                "            \"N\"",
                "        )",
                ")"
              ],
              "type": "calculated"
            }
          }
        ]
      },
      {
        "name": "DateTableTemplate_d8ff267f-2e67-4d2c-9fc2-906d6fc4043c",
        "annotations": [
          {
            "name": "__PBI_TemplateDateTable",
            "value": "true"
          },
          {
            "name": "DefaultItem",
            "value": "DateHierarchy"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "formatString": "General Date",
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "d965f7e0-4330-429b-b0a9-5912620f9c02",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "ec1385d5-8345-4135-8177-bc32e0806ea8",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "25c0c5cc-b90c-4b31-b620-984ef5a4124f",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isHidden": true,
            "lineageTag": "dc8143f6-6b6b-42cb-9639-eb8145ab33b7",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "ea656df0-94f6-4537-b9b4-1de23341a9c6",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Quarter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Qtr \" & [QuarterNo]",
            "isHidden": true,
            "lineageTag": "f0585822-5dd6-459d-bc17-f29c619c9c05",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Day",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "75316963-8dcf-4910-9ac2-037877d4f79a",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Date Hierarchy",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Year",
                "column": "Year",
                "lineageTag": "ac07dbd8-41d7-48e6-b2e2-2a04f1d8179d",
                "ordinal": 0
              },
              {
                "name": "Quarter",
                "column": "Quarter",
                "lineageTag": "3f1fabae-efa4-48c6-bc68-d5709c9b7b9e",
                "ordinal": 1
              },
              {
                "name": "Month",
                "column": "Month",
                "lineageTag": "ab72b66b-8fcc-4a2e-aff2-b459e3937883",
                "ordinal": 2
              },
              {
                "name": "Day",
                "column": "Day",
                "lineageTag": "f99b19bf-6b44-44aa-951c-55c79dbf9424",
                "ordinal": 3
              }
            ],
            "lineageTag": "a7edd956-2f35-4909-8147-1bf8c03a4ece"
          }
        ],
        "isHidden": true,
        "isPrivate": true,
        "lineageTag": "b5766227-6d7b-44eb-b991-2414398c99ba",
        "partitions": [
          {
            "name": "DateTableTemplate_d8ff267f-2e67-4d2c-9fc2-906d6fc4043c",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(2015,1,1), Date(2015,1,1))",
              "type": "calculated"
            }
          }
        ]
      },
      {
        "name": "LocalDateTable_32e1f282-8cf9-463b-9322-a13d5ca45473",
        "annotations": [
          {
            "name": "__PBI_LocalDateTable",
            "value": "true"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "formatString": "General Date",
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "c7675b14-0923-4fe9-961d-bdee0784ce95",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "b1b02560-e7e0-4555-ae8c-0e2f8d849900",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "e5b60961-c830-4d45-bb4d-b9c003ecf6f5",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isHidden": true,
            "lineageTag": "ff82cc38-4e74-4d88-bcf4-16a1f7fa56ae",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "81724443-4f7b-473d-b76a-e3b237ecd20f",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Quarter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Qtr \" & [QuarterNo]",
            "isHidden": true,
            "lineageTag": "f8921654-9cd1-4cb2-88ab-32d81b3a4fac",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Day",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "a5026ca7-aa23-40a8-ba18-53bc8aeda231",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Date Hierarchy",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Year",
                "column": "Year",
                "lineageTag": "95538929-4d55-438b-ad2e-95ae50ccb1f9",
                "ordinal": 0
              },
              {
                "name": "Quarter",
                "column": "Quarter",
                "lineageTag": "32b21537-4bd0-4940-bb55-1620fef23902",
                "ordinal": 1
              },
              {
                "name": "Month",
                "column": "Month",
                "lineageTag": "5c2748ba-6421-40ae-974c-e0e737a992dc",
                "ordinal": 2
              },
              {
                "name": "Day",
                "column": "Day",
                "lineageTag": "3102459c-b836-442e-8648-1fc0ee40c162",
                "ordinal": 3
              }
            ],
            "lineageTag": "3cc9c8e7-77d1-43fe-abb3-69c89b5fd959"
          }
        ],
        "isHidden": true,
        "lineageTag": "0ea247a3-7ca2-4337-8d33-ab41ff750d97",
        "partitions": [
          {
            "name": "LocalDateTable_32e1f282-8cf9-463b-9322-a13d5ca45473",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(Year(MIN('dCalendario'[Date])), 1, 1), Date(Year(MAX('dCalendario'[Date])), 12, 31))",
              "type": "calculated"
            }
          }
        ],
        "showAsVariationsOnly": true
      }
    ]
  }
}